package cn.xy.novelwebproject.bean;

import java.util.Arrays;
import java.util.List;

public class Author {
		/**
		 * This field was generated by MyBatis Generator.
		 * This field corresponds to the database column author.nick_name
		 *
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		private String nick_name;

		/**
		 * This field was generated by MyBatis Generator.
		 * This field corresponds to the database column author.sex
		 *
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		private String sex;

		/**
		 * This field was generated by MyBatis Generator.
		 * This field corresponds to the database column author.subscriptions
		 *
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		private Integer subscriptions;

		/**
		 * This field was generated by MyBatis Generator.
		 * This field corresponds to the database column author.collections
		 *
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		private Integer collections;

		/**
		 * This field was generated by MyBatis Generator.
		 * This field corresponds to the database column author.concerns
		 *
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		private Integer concerns;

		/**
		 * This field was generated by MyBatis Generator.
		 * This field corresponds to the database column author.footmark
		 *
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		private List<Footmarks> footmark;

		/**
		 * This field was generated by MyBatis Generator.
		 * This field corresponds to the database column author.works
		 *
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		private List<Novel> works;

		/**
		 * This field was generated by MyBatis Generator.
		 * This field corresponds to the database column author.fans
		 *
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		private Integer fans;

		private String password;

		private String headimage;
		/**
		 * This method was generated by MyBatis Generator.
		 * This method returns the value of the database column author.nick_name
		 *
		 * @return the value of author.nick_name
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		public String getNick_name () {
				return nick_name;
		}

		public String getHeadimage() {
				return headimage;
		}

		public void setHeadimage(String headimage) {
				this.headimage = headimage;
		}

		/**
		 * This method was generated by MyBatis Generator.
		 * This method sets the value of the database column author.nick_name
		 *
		 * @param nick_name the value for author.nick_name
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		public void setNick_name (String nick_name) {
				this.nick_name = nick_name == null ? null : nick_name.trim();
		}

		/**
		 * This method was generated by MyBatis Generator.
		 * This method returns the value of the database column author.sex
		 *
		 * @return the value of author.sex
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		public String getSex () {
				return sex;
		}

		/**
		 * This method was generated by MyBatis Generator.
		 * This method sets the value of the database column author.sex
		 *
		 * @param sex the value for author.sex
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		public void setSex (String sex) {
				this.sex = sex == null ? null : sex.trim();
		}

		/**
		 * This method was generated by MyBatis Generator.
		 * This method returns the value of the database column author.subscriptions
		 *
		 * @return the value of author.subscriptions
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		public Integer getSubscriptions () {
				return subscriptions;
		}

		/**
		 * This method was generated by MyBatis Generator.
		 * This method sets the value of the database column author.subscriptions
		 *
		 * @param subscriptions the value for author.subscriptions
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		public void setSubscriptions (Integer subscriptions) {
				this.subscriptions = subscriptions;
		}

		/**
		 * This method was generated by MyBatis Generator.
		 * This method returns the value of the database column author.collections
		 *
		 * @return the value of author.collections
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		public Integer getCollections () {
				return collections;
		}

		/**
		 * This method was generated by MyBatis Generator.
		 * This method sets the value of the database column author.collections
		 *
		 * @param collections the value for author.collections
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		public void setCollections (Integer collections) {
				this.collections = collections;
		}

		/**
		 * This method was generated by MyBatis Generator.
		 * This method returns the value of the database column author.concerns
		 *
		 * @return the value of author.concerns
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		public Integer getConcerns () {
				return concerns;
		}

		/**
		 * This method was generated by MyBatis Generator.
		 * This method sets the value of the database column author.concerns
		 *
		 * @param concerns the value for author.concerns
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		public void setConcerns (Integer concerns) {
				this.concerns = concerns;
		}

		public List<Footmarks> getFootmark () {
				return footmark;
		}

		public void setFootmark (List<Footmarks> footmark) {
				this.footmark = footmark;
		}

		public List<Novel> getWorks () {
				return works;
		}

		public void setWorks (List<Novel> works) {
				this.works = works;
		}

		/**
		 * This method was generated by MyBatis Generator.
		 * This method returns the value of the database column author.fans
		 *
		 * @return the value of author.fans
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		public Integer getFans () {
				return fans;
		}

		/**
		 * This method was generated by MyBatis Generator.
		 * This method sets the value of the database column author.fans
		 *
		 * @param fans the value for author.fans
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		public void setFans (Integer fans) {
				this.fans = fans;
		}

		public String getPassword () {
				return password;
		}

		public void setPassword (String password) {
				this.password = password;
		}

		@Override
		public String toString() {
				return "Author{" +
					"nick_name='" + nick_name + '\'' +
					", sex='" + sex + '\'' +
					", subscriptions=" + subscriptions +
					", collections=" + collections +
					", concerns=" + concerns +
					", footmark=" + footmark +
					", works=" + works +
					", fans=" + fans +
					", password='" + password + '\'' +
					", headimage='" + headimage + '\'' +
					'}';
		}
}