package cn.xy.novelwebproject.bean;

import java.util.ArrayList;
import java.util.List;

public class AuthorExample {
		/**
		 * This field was generated by MyBatis Generator.
		 * This field corresponds to the database table author
		 *
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		protected String orderByClause;

		/**
		 * This field was generated by MyBatis Generator.
		 * This field corresponds to the database table author
		 *
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		protected boolean distinct;

		/**
		 * This field was generated by MyBatis Generator.
		 * This field corresponds to the database table author
		 *
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		protected List<Criteria> oredCriteria;

		/**
		 * This method was generated by MyBatis Generator.
		 * This method corresponds to the database table author
		 *
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		public AuthorExample () {
				oredCriteria = new ArrayList<Criteria>();
		}

		/**
		 * This method was generated by MyBatis Generator.
		 * This method corresponds to the database table author
		 *
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		public void setOrderByClause (String orderByClause) {
				this.orderByClause = orderByClause;
		}

		/**
		 * This method was generated by MyBatis Generator.
		 * This method corresponds to the database table author
		 *
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		public String getOrderByClause () {
				return orderByClause;
		}

		/**
		 * This method was generated by MyBatis Generator.
		 * This method corresponds to the database table author
		 *
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		public void setDistinct (boolean distinct) {
				this.distinct = distinct;
		}

		/**
		 * This method was generated by MyBatis Generator.
		 * This method corresponds to the database table author
		 *
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		public boolean isDistinct () {
				return distinct;
		}

		/**
		 * This method was generated by MyBatis Generator.
		 * This method corresponds to the database table author
		 *
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		public List<Criteria> getOredCriteria () {
				return oredCriteria;
		}

		/**
		 * This method was generated by MyBatis Generator.
		 * This method corresponds to the database table author
		 *
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		public void or (Criteria criteria) {
				oredCriteria.add(criteria);
		}

		/**
		 * This method was generated by MyBatis Generator.
		 * This method corresponds to the database table author
		 *
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		public Criteria or () {
				Criteria criteria = createCriteriaInternal();
				oredCriteria.add(criteria);
				return criteria;
		}

		/**
		 * This method was generated by MyBatis Generator.
		 * This method corresponds to the database table author
		 *
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		public Criteria createCriteria () {
				Criteria criteria = createCriteriaInternal();
				if (oredCriteria.size() == 0) {
						oredCriteria.add(criteria);
				}
				return criteria;
		}

		/**
		 * This method was generated by MyBatis Generator.
		 * This method corresponds to the database table author
		 *
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		protected Criteria createCriteriaInternal () {
				Criteria criteria = new Criteria();
				return criteria;
		}

		/**
		 * This method was generated by MyBatis Generator.
		 * This method corresponds to the database table author
		 *
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		public void clear () {
				oredCriteria.clear();
				orderByClause = null;
				distinct = false;
		}

		/**
		 * This class was generated by MyBatis Generator.
		 * This class corresponds to the database table author
		 *
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		protected abstract static class GeneratedCriteria {
				protected List<Criterion> criteria;

				protected GeneratedCriteria () {
						super();
						criteria = new ArrayList<Criterion>();
				}

				public boolean isValid () {
						return criteria.size() > 0;
				}

				public List<Criterion> getAllCriteria () {
						return criteria;
				}

				public List<Criterion> getCriteria () {
						return criteria;
				}

				protected void addCriterion (String condition) {
						if (condition == null) {
								throw new RuntimeException("Value for condition cannot be null");
						}
						criteria.add(new Criterion(condition));
				}

				protected void addCriterion (String condition, Object value, String property) {
						if (value == null) {
								throw new RuntimeException("Value for " + property + " cannot be null");
						}
						criteria.add(new Criterion(condition, value));
				}

				protected void addCriterion (String condition, Object value1, Object value2, String property) {
						if (value1 == null || value2 == null) {
								throw new RuntimeException("Between values for " + property + " cannot be null");
						}
						criteria.add(new Criterion(condition, value1, value2));
				}

				public Criteria andNick_nameIsNull () {
						addCriterion("nick_name is null");
						return (Criteria) this;
				}

				public Criteria andNick_nameIsNotNull () {
						addCriterion("nick_name is not null");
						return (Criteria) this;
				}

				public Criteria andNick_nameEqualTo (String value) {
						addCriterion("nick_name =", value, "nick_name");
						return (Criteria) this;
				}

				public Criteria andNick_nameNotEqualTo (String value) {
						addCriterion("nick_name <>", value, "nick_name");
						return (Criteria) this;
				}

				public Criteria andNick_nameGreaterThan (String value) {
						addCriterion("nick_name >", value, "nick_name");
						return (Criteria) this;
				}

				public Criteria andNick_nameGreaterThanOrEqualTo (String value) {
						addCriterion("nick_name >=", value, "nick_name");
						return (Criteria) this;
				}

				public Criteria andNick_nameLessThan (String value) {
						addCriterion("nick_name <", value, "nick_name");
						return (Criteria) this;
				}

				public Criteria andNick_nameLessThanOrEqualTo (String value) {
						addCriterion("nick_name <=", value, "nick_name");
						return (Criteria) this;
				}

				public Criteria andNick_nameLike (String value) {
						addCriterion("nick_name like", value, "nick_name");
						return (Criteria) this;
				}

				public Criteria andNick_nameNotLike (String value) {
						addCriterion("nick_name not like", value, "nick_name");
						return (Criteria) this;
				}

				public Criteria andNick_nameIn (List<String> values) {
						addCriterion("nick_name in", values, "nick_name");
						return (Criteria) this;
				}

				public Criteria andNick_nameNotIn (List<String> values) {
						addCriterion("nick_name not in", values, "nick_name");
						return (Criteria) this;
				}

				public Criteria andNick_nameBetween (String value1, String value2) {
						addCriterion("nick_name between", value1, value2, "nick_name");
						return (Criteria) this;
				}

				public Criteria andNick_nameNotBetween (String value1, String value2) {
						addCriterion("nick_name not between", value1, value2, "nick_name");
						return (Criteria) this;
				}

				public Criteria andSexIsNull () {
						addCriterion("sex is null");
						return (Criteria) this;
				}

				public Criteria andSexIsNotNull () {
						addCriterion("sex is not null");
						return (Criteria) this;
				}

				public Criteria andSexEqualTo (String value) {
						addCriterion("sex =", value, "sex");
						return (Criteria) this;
				}

				public Criteria andSexNotEqualTo (String value) {
						addCriterion("sex <>", value, "sex");
						return (Criteria) this;
				}

				public Criteria andSexGreaterThan (String value) {
						addCriterion("sex >", value, "sex");
						return (Criteria) this;
				}

				public Criteria andSexGreaterThanOrEqualTo (String value) {
						addCriterion("sex >=", value, "sex");
						return (Criteria) this;
				}

				public Criteria andSexLessThan (String value) {
						addCriterion("sex <", value, "sex");
						return (Criteria) this;
				}

				public Criteria andSexLessThanOrEqualTo (String value) {
						addCriterion("sex <=", value, "sex");
						return (Criteria) this;
				}

				public Criteria andSexLike (String value) {
						addCriterion("sex like", value, "sex");
						return (Criteria) this;
				}

				public Criteria andSexNotLike (String value) {
						addCriterion("sex not like", value, "sex");
						return (Criteria) this;
				}

				public Criteria andSexIn (List<String> values) {
						addCriterion("sex in", values, "sex");
						return (Criteria) this;
				}

				public Criteria andSexNotIn (List<String> values) {
						addCriterion("sex not in", values, "sex");
						return (Criteria) this;
				}

				public Criteria andSexBetween (String value1, String value2) {
						addCriterion("sex between", value1, value2, "sex");
						return (Criteria) this;
				}

				public Criteria andSexNotBetween (String value1, String value2) {
						addCriterion("sex not between", value1, value2, "sex");
						return (Criteria) this;
				}

				public Criteria andSubscriptionsIsNull () {
						addCriterion("subscriptions is null");
						return (Criteria) this;
				}

				public Criteria andSubscriptionsIsNotNull () {
						addCriterion("subscriptions is not null");
						return (Criteria) this;
				}

				public Criteria andSubscriptionsEqualTo (Integer value) {
						addCriterion("subscriptions =", value, "subscriptions");
						return (Criteria) this;
				}

				public Criteria andSubscriptionsNotEqualTo (Integer value) {
						addCriterion("subscriptions <>", value, "subscriptions");
						return (Criteria) this;
				}

				public Criteria andSubscriptionsGreaterThan (Integer value) {
						addCriterion("subscriptions >", value, "subscriptions");
						return (Criteria) this;
				}

				public Criteria andSubscriptionsGreaterThanOrEqualTo (Integer value) {
						addCriterion("subscriptions >=", value, "subscriptions");
						return (Criteria) this;
				}

				public Criteria andSubscriptionsLessThan (Integer value) {
						addCriterion("subscriptions <", value, "subscriptions");
						return (Criteria) this;
				}

				public Criteria andSubscriptionsLessThanOrEqualTo (Integer value) {
						addCriterion("subscriptions <=", value, "subscriptions");
						return (Criteria) this;
				}

				public Criteria andSubscriptionsIn (List<Integer> values) {
						addCriterion("subscriptions in", values, "subscriptions");
						return (Criteria) this;
				}

				public Criteria andSubscriptionsNotIn (List<Integer> values) {
						addCriterion("subscriptions not in", values, "subscriptions");
						return (Criteria) this;
				}

				public Criteria andSubscriptionsBetween (Integer value1, Integer value2) {
						addCriterion("subscriptions between", value1, value2, "subscriptions");
						return (Criteria) this;
				}

				public Criteria andSubscriptionsNotBetween (Integer value1, Integer value2) {
						addCriterion("subscriptions not between", value1, value2, "subscriptions");
						return (Criteria) this;
				}

				public Criteria andCollectionsIsNull () {
						addCriterion("collections is null");
						return (Criteria) this;
				}

				public Criteria andCollectionsIsNotNull () {
						addCriterion("collections is not null");
						return (Criteria) this;
				}

				public Criteria andCollectionsEqualTo (Integer value) {
						addCriterion("collections =", value, "collections");
						return (Criteria) this;
				}

				public Criteria andCollectionsNotEqualTo (Integer value) {
						addCriterion("collections <>", value, "collections");
						return (Criteria) this;
				}

				public Criteria andCollectionsGreaterThan (Integer value) {
						addCriterion("collections >", value, "collections");
						return (Criteria) this;
				}

				public Criteria andCollectionsGreaterThanOrEqualTo (Integer value) {
						addCriterion("collections >=", value, "collections");
						return (Criteria) this;
				}

				public Criteria andCollectionsLessThan (Integer value) {
						addCriterion("collections <", value, "collections");
						return (Criteria) this;
				}

				public Criteria andCollectionsLessThanOrEqualTo (Integer value) {
						addCriterion("collections <=", value, "collections");
						return (Criteria) this;
				}

				public Criteria andCollectionsIn (List<Integer> values) {
						addCriterion("collections in", values, "collections");
						return (Criteria) this;
				}

				public Criteria andCollectionsNotIn (List<Integer> values) {
						addCriterion("collections not in", values, "collections");
						return (Criteria) this;
				}

				public Criteria andCollectionsBetween (Integer value1, Integer value2) {
						addCriterion("collections between", value1, value2, "collections");
						return (Criteria) this;
				}

				public Criteria andCollectionsNotBetween (Integer value1, Integer value2) {
						addCriterion("collections not between", value1, value2, "collections");
						return (Criteria) this;
				}

				public Criteria andConcernsIsNull () {
						addCriterion("concerns is null");
						return (Criteria) this;
				}

				public Criteria andConcernsIsNotNull () {
						addCriterion("concerns is not null");
						return (Criteria) this;
				}

				public Criteria andConcernsEqualTo (Integer value) {
						addCriterion("concerns =", value, "concerns");
						return (Criteria) this;
				}

				public Criteria andConcernsNotEqualTo (Integer value) {
						addCriterion("concerns <>", value, "concerns");
						return (Criteria) this;
				}

				public Criteria andConcernsGreaterThan (Integer value) {
						addCriterion("concerns >", value, "concerns");
						return (Criteria) this;
				}

				public Criteria andConcernsGreaterThanOrEqualTo (Integer value) {
						addCriterion("concerns >=", value, "concerns");
						return (Criteria) this;
				}

				public Criteria andConcernsLessThan (Integer value) {
						addCriterion("concerns <", value, "concerns");
						return (Criteria) this;
				}

				public Criteria andConcernsLessThanOrEqualTo (Integer value) {
						addCriterion("concerns <=", value, "concerns");
						return (Criteria) this;
				}

				public Criteria andConcernsIn (List<Integer> values) {
						addCriterion("concerns in", values, "concerns");
						return (Criteria) this;
				}

				public Criteria andConcernsNotIn (List<Integer> values) {
						addCriterion("concerns not in", values, "concerns");
						return (Criteria) this;
				}

				public Criteria andConcernsBetween (Integer value1, Integer value2) {
						addCriterion("concerns between", value1, value2, "concerns");
						return (Criteria) this;
				}

				public Criteria andConcernsNotBetween (Integer value1, Integer value2) {
						addCriterion("concerns not between", value1, value2, "concerns");
						return (Criteria) this;
				}

				public Criteria andFootmarkIsNull () {
						addCriterion("footmark is null");
						return (Criteria) this;
				}

				public Criteria andFootmarkIsNotNull () {
						addCriterion("footmark is not null");
						return (Criteria) this;
				}

				public Criteria andFootmarkEqualTo (String value) {
						addCriterion("footmark =", value, "footmark");
						return (Criteria) this;
				}

				public Criteria andFootmarkNotEqualTo (String value) {
						addCriterion("footmark <>", value, "footmark");
						return (Criteria) this;
				}

				public Criteria andFootmarkGreaterThan (String value) {
						addCriterion("footmark >", value, "footmark");
						return (Criteria) this;
				}

				public Criteria andFootmarkGreaterThanOrEqualTo (String value) {
						addCriterion("footmark >=", value, "footmark");
						return (Criteria) this;
				}

				public Criteria andFootmarkLessThan (String value) {
						addCriterion("footmark <", value, "footmark");
						return (Criteria) this;
				}

				public Criteria andFootmarkLessThanOrEqualTo (String value) {
						addCriterion("footmark <=", value, "footmark");
						return (Criteria) this;
				}

				public Criteria andFootmarkLike (String value) {
						addCriterion("footmark like", value, "footmark");
						return (Criteria) this;
				}

				public Criteria andFootmarkNotLike (String value) {
						addCriterion("footmark not like", value, "footmark");
						return (Criteria) this;
				}

				public Criteria andFootmarkIn (List<String> values) {
						addCriterion("footmark in", values, "footmark");
						return (Criteria) this;
				}

				public Criteria andFootmarkNotIn (List<String> values) {
						addCriterion("footmark not in", values, "footmark");
						return (Criteria) this;
				}

				public Criteria andFootmarkBetween (String value1, String value2) {
						addCriterion("footmark between", value1, value2, "footmark");
						return (Criteria) this;
				}

				public Criteria andFootmarkNotBetween (String value1, String value2) {
						addCriterion("footmark not between", value1, value2, "footmark");
						return (Criteria) this;
				}

				public Criteria andWorksIsNull () {
						addCriterion("works is null");
						return (Criteria) this;
				}

				public Criteria andWorksIsNotNull () {
						addCriterion("works is not null");
						return (Criteria) this;
				}

				public Criteria andWorksEqualTo (String value) {
						addCriterion("works =", value, "works");
						return (Criteria) this;
				}

				public Criteria andWorksNotEqualTo (String value) {
						addCriterion("works <>", value, "works");
						return (Criteria) this;
				}

				public Criteria andWorksGreaterThan (String value) {
						addCriterion("works >", value, "works");
						return (Criteria) this;
				}

				public Criteria andWorksGreaterThanOrEqualTo (String value) {
						addCriterion("works >=", value, "works");
						return (Criteria) this;
				}

				public Criteria andWorksLessThan (String value) {
						addCriterion("works <", value, "works");
						return (Criteria) this;
				}

				public Criteria andWorksLessThanOrEqualTo (String value) {
						addCriterion("works <=", value, "works");
						return (Criteria) this;
				}

				public Criteria andWorksLike (String value) {
						addCriterion("works like", value, "works");
						return (Criteria) this;
				}

				public Criteria andWorksNotLike (String value) {
						addCriterion("works not like", value, "works");
						return (Criteria) this;
				}

				public Criteria andWorksIn (List<String> values) {
						addCriterion("works in", values, "works");
						return (Criteria) this;
				}

				public Criteria andWorksNotIn (List<String> values) {
						addCriterion("works not in", values, "works");
						return (Criteria) this;
				}

				public Criteria andWorksBetween (String value1, String value2) {
						addCriterion("works between", value1, value2, "works");
						return (Criteria) this;
				}

				public Criteria andWorksNotBetween (String value1, String value2) {
						addCriterion("works not between", value1, value2, "works");
						return (Criteria) this;
				}

				public Criteria andFansIsNull () {
						addCriterion("fans is null");
						return (Criteria) this;
				}

				public Criteria andFansIsNotNull () {
						addCriterion("fans is not null");
						return (Criteria) this;
				}

				public Criteria andFansEqualTo (Integer value) {
						addCriterion("fans =", value, "fans");
						return (Criteria) this;
				}

				public Criteria andFansNotEqualTo (Integer value) {
						addCriterion("fans <>", value, "fans");
						return (Criteria) this;
				}

				public Criteria andFansGreaterThan (Integer value) {
						addCriterion("fans >", value, "fans");
						return (Criteria) this;
				}

				public Criteria andFansGreaterThanOrEqualTo (Integer value) {
						addCriterion("fans >=", value, "fans");
						return (Criteria) this;
				}

				public Criteria andFansLessThan (Integer value) {
						addCriterion("fans <", value, "fans");
						return (Criteria) this;
				}

				public Criteria andFansLessThanOrEqualTo (Integer value) {
						addCriterion("fans <=", value, "fans");
						return (Criteria) this;
				}

				public Criteria andFansIn (List<Integer> values) {
						addCriterion("fans in", values, "fans");
						return (Criteria) this;
				}

				public Criteria andFansNotIn (List<Integer> values) {
						addCriterion("fans not in", values, "fans");
						return (Criteria) this;
				}

				public Criteria andFansBetween (Integer value1, Integer value2) {
						addCriterion("fans between", value1, value2, "fans");
						return (Criteria) this;
				}

				public Criteria andFansNotBetween (Integer value1, Integer value2) {
						addCriterion("fans not between", value1, value2, "fans");
						return (Criteria) this;
				}
		}

		/**
		 * This class was generated by MyBatis Generator.
		 * This class corresponds to the database table author
		 *
		 * @mbg.generated do_not_delete_during_merge Sat Jun 06 19:29:15 CST 2020
		 */
		public static class Criteria extends GeneratedCriteria {

				protected Criteria () {
						super();
				}
		}

		/**
		 * This class was generated by MyBatis Generator.
		 * This class corresponds to the database table author
		 *
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		public static class Criterion {
				private String condition;

				private Object value;

				private Object secondValue;

				private boolean noValue;

				private boolean singleValue;

				private boolean betweenValue;

				private boolean listValue;

				private String typeHandler;

				public String getCondition () {
						return condition;
				}

				public Object getValue () {
						return value;
				}

				public Object getSecondValue () {
						return secondValue;
				}

				public boolean isNoValue () {
						return noValue;
				}

				public boolean isSingleValue () {
						return singleValue;
				}

				public boolean isBetweenValue () {
						return betweenValue;
				}

				public boolean isListValue () {
						return listValue;
				}

				public String getTypeHandler () {
						return typeHandler;
				}

				protected Criterion (String condition) {
						super();
						this.condition = condition;
						this.typeHandler = null;
						this.noValue = true;
				}

				protected Criterion (String condition, Object value, String typeHandler) {
						super();
						this.condition = condition;
						this.value = value;
						this.typeHandler = typeHandler;
						if (value instanceof List<?>) {
								this.listValue = true;
						} else {
								this.singleValue = true;
						}
				}

				protected Criterion (String condition, Object value) {
						this(condition, value, null);
				}

				protected Criterion (String condition, Object value, Object secondValue, String typeHandler) {
						super();
						this.condition = condition;
						this.value = value;
						this.secondValue = secondValue;
						this.typeHandler = typeHandler;
						this.betweenValue = true;
				}

				protected Criterion (String condition, Object value, Object secondValue) {
						this(condition, value, secondValue, null);
				}
		}
}