package cn.xy.novelwebproject.bean;

import java.util.Date;

public class Catalog {

		private int id;

		private String novel_name;

		private String novale_catalog;

		private Date updatetime;

		/**
		 * This method was generated by MyBatis Generator.
		 * This method returns the value of the database column catalog.novel_name
		 *
		 * @return the value of catalog.novel_name
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		public String getNovel_name () {
				return novel_name;
		}

		/**
		 * This method was generated by MyBatis Generator.
		 * This method sets the value of the database column catalog.novel_name
		 *
		 * @param novel_name the value for catalog.novel_name
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		public void setNovel_name (String novel_name) {
				this.novel_name = novel_name == null ? null : novel_name.trim();
		}

		/**
		 * This method was generated by MyBatis Generator.
		 * This method returns the value of the database column catalog.novale_catalog
		 *
		 * @return the value of catalog.novale_catalog
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		public String getNovale_catalog () {
				return novale_catalog;
		}

		/**
		 * This method was generated by MyBatis Generator.
		 * This method sets the value of the database column catalog.novale_catalog
		 *
		 * @param novale_catalog the value for catalog.novale_catalog
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		public void setNovale_catalog (String novale_catalog) {
				this.novale_catalog = novale_catalog == null ? null : novale_catalog.trim();
		}

		/**
		 * This method was generated by MyBatis Generator.
		 * This method returns the value of the database column catalog.updatetime
		 *
		 * @return the value of catalog.updatetime
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		public Date getUpdatetime () {
				return updatetime;
		}

		/**
		 * This method was generated by MyBatis Generator.
		 * This method sets the value of the database column catalog.updatetime
		 *
		 * @param updatetime the value for catalog.updatetime
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		public void setUpdatetime (Date updatetime) {
				this.updatetime = updatetime;
		}

		public int getId () {
				return id;
		}

		public void setId (int id) {
				this.id = id;
		}


		@Override
		public String toString () {
				return "Catalog{" +
						"id=" + id +
						", novel_name='" + novel_name + '\'' +
						", novale_catalog='" + novale_catalog + '\'' +
						", updatetime=" + updatetime +
						'}';
		}
}