package cn.xy.novelwebproject.bean;

import java.util.Date;

public class Comment {
		/**
		 * This field was generated by MyBatis Generator.
		 * This field corresponds to the database column comment.id
		 *
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		private String id;

		/**
		 * This field was generated by MyBatis Generator.
		 * This field corresponds to the database column comment.comment_title
		 *
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		private String comment_title;

		/**
		 * This field was generated by MyBatis Generator.
		 * This field corresponds to the database column comment.comment_context
		 *
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		private String comment_context;

		/**
		 * This field was generated by MyBatis Generator.
		 * This field corresponds to the database column comment.comment_author
		 *
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		private String comment_author;

		/**
		 * This field was generated by MyBatis Generator.
		 * This field corresponds to the database column comment.comment_time
		 *
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		private Date comment_time;

		/**
		 * This field was generated by MyBatis Generator.
		 * This field corresponds to the database column comment.comment_url
		 *
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		private String comment_url;

		/**
		 * This method was generated by MyBatis Generator.
		 * This method returns the value of the database column comment.id
		 *
		 * @return the value of comment.id
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		public String getId () {
				return id;
		}

		/**
		 * This method was generated by MyBatis Generator.
		 * This method sets the value of the database column comment.id
		 *
		 * @param id the value for comment.id
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		public void setId (String id) {
				this.id = id == null ? null : id.trim();
		}

		/**
		 * This method was generated by MyBatis Generator.
		 * This method returns the value of the database column comment.comment_title
		 *
		 * @return the value of comment.comment_title
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		public String getComment_title () {
				return comment_title;
		}

		/**
		 * This method was generated by MyBatis Generator.
		 * This method sets the value of the database column comment.comment_title
		 *
		 * @param comment_title the value for comment.comment_title
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		public void setComment_title (String comment_title) {
				this.comment_title = comment_title == null ? null : comment_title.trim();
		}

		/**
		 * This method was generated by MyBatis Generator.
		 * This method returns the value of the database column comment.comment_context
		 *
		 * @return the value of comment.comment_context
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		public String getComment_context () {
				return comment_context;
		}

		/**
		 * This method was generated by MyBatis Generator.
		 * This method sets the value of the database column comment.comment_context
		 *
		 * @param comment_context the value for comment.comment_context
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		public void setComment_context (String comment_context) {
				this.comment_context = comment_context == null ? null : comment_context.trim();
		}

		/**
		 * This method was generated by MyBatis Generator.
		 * This method returns the value of the database column comment.comment_author
		 *
		 * @return the value of comment.comment_author
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		public String getComment_author () {
				return comment_author;
		}

		/**
		 * This method was generated by MyBatis Generator.
		 * This method sets the value of the database column comment.comment_author
		 *
		 * @param comment_author the value for comment.comment_author
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		public void setComment_author (String comment_author) {
				this.comment_author = comment_author == null ? null : comment_author.trim();
		}

		/**
		 * This method was generated by MyBatis Generator.
		 * This method returns the value of the database column comment.comment_time
		 *
		 * @return the value of comment.comment_time
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		public Date getComment_time () {
				return comment_time;
		}

		/**
		 * This method was generated by MyBatis Generator.
		 * This method sets the value of the database column comment.comment_time
		 *
		 * @param comment_time the value for comment.comment_time
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		public void setComment_time (Date comment_time) {
				this.comment_time = comment_time;
		}

		/**
		 * This method was generated by MyBatis Generator.
		 * This method returns the value of the database column comment.comment_url
		 *
		 * @return the value of comment.comment_url
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		public String getComment_url () {
				return comment_url;
		}

		/**
		 * This method was generated by MyBatis Generator.
		 * This method sets the value of the database column comment.comment_url
		 *
		 * @param comment_url the value for comment.comment_url
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		public void setComment_url (String comment_url) {
				this.comment_url = comment_url == null ? null : comment_url.trim();
		}

		@Override
		public String toString () {
				return "Comment{" +
						"id='" + id + '\'' +
						", comment_title='" + comment_title + '\'' +
						", comment_context='" + comment_context + '\'' +
						", comment_author='" + comment_author + '\'' +
						", comment_time=" + comment_time +
						", comment_url='" + comment_url + '\'' +
						'}';
		}
}