package cn.xy.novelwebproject.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class NovelExample {
		/**
		 * This field was generated by MyBatis Generator.
		 * This field corresponds to the database table novel
		 *
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		protected String orderByClause;

		/**
		 * This field was generated by MyBatis Generator.
		 * This field corresponds to the database table novel
		 *
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		protected boolean distinct;

		/**
		 * This field was generated by MyBatis Generator.
		 * This field corresponds to the database table novel
		 *
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		protected List<Criteria> oredCriteria;

		/**
		 * This method was generated by MyBatis Generator.
		 * This method corresponds to the database table novel
		 *
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		public NovelExample () {
				oredCriteria = new ArrayList<Criteria>();
		}

		/**
		 * This method was generated by MyBatis Generator.
		 * This method corresponds to the database table novel
		 *
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		public void setOrderByClause (String orderByClause) {
				this.orderByClause = orderByClause;
		}

		/**
		 * This method was generated by MyBatis Generator.
		 * This method corresponds to the database table novel
		 *
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		public String getOrderByClause () {
				return orderByClause;
		}

		/**
		 * This method was generated by MyBatis Generator.
		 * This method corresponds to the database table novel
		 *
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		public void setDistinct (boolean distinct) {
				this.distinct = distinct;
		}

		/**
		 * This method was generated by MyBatis Generator.
		 * This method corresponds to the database table novel
		 *
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		public boolean isDistinct () {
				return distinct;
		}

		/**
		 * This method was generated by MyBatis Generator.
		 * This method corresponds to the database table novel
		 *
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		public List<Criteria> getOredCriteria () {
				return oredCriteria;
		}

		/**
		 * This method was generated by MyBatis Generator.
		 * This method corresponds to the database table novel
		 *
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		public void or (Criteria criteria) {
				oredCriteria.add(criteria);
		}

		/**
		 * This method was generated by MyBatis Generator.
		 * This method corresponds to the database table novel
		 *
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		public Criteria or () {
				Criteria criteria = createCriteriaInternal();
				oredCriteria.add(criteria);
				return criteria;
		}

		/**
		 * This method was generated by MyBatis Generator.
		 * This method corresponds to the database table novel
		 *
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		public Criteria createCriteria () {
				Criteria criteria = createCriteriaInternal();
				if (oredCriteria.size() == 0) {
						oredCriteria.add(criteria);
				}
				return criteria;
		}

		/**
		 * This method was generated by MyBatis Generator.
		 * This method corresponds to the database table novel
		 *
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		protected Criteria createCriteriaInternal () {
				Criteria criteria = new Criteria();
				return criteria;
		}

		/**
		 * This method was generated by MyBatis Generator.
		 * This method corresponds to the database table novel
		 *
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		public void clear () {
				oredCriteria.clear();
				orderByClause = null;
				distinct = false;
		}

		/**
		 * This class was generated by MyBatis Generator.
		 * This class corresponds to the database table novel
		 *
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		protected abstract static class GeneratedCriteria {
				protected List<Criterion> criteria;

				protected GeneratedCriteria () {
						super();
						criteria = new ArrayList<Criterion>();
				}

				public boolean isValid () {
						return criteria.size() > 0;
				}

				public List<Criterion> getAllCriteria () {
						return criteria;
				}

				public List<Criterion> getCriteria () {
						return criteria;
				}

				protected void addCriterion (String condition) {
						if (condition == null) {
								throw new RuntimeException("Value for condition cannot be null");
						}
						criteria.add(new Criterion(condition));
				}

				protected void addCriterion (String condition, Object value, String property) {
						if (value == null) {
								throw new RuntimeException("Value for " + property + " cannot be null");
						}
						criteria.add(new Criterion(condition, value));
				}

				protected void addCriterion (String condition, Object value1, Object value2, String property) {
						if (value1 == null || value2 == null) {
								throw new RuntimeException("Between values for " + property + " cannot be null");
						}
						criteria.add(new Criterion(condition, value1, value2));
				}

				protected void addCriterionForJDBCDate (String condition, Date value, String property) {
						if (value == null) {
								throw new RuntimeException("Value for " + property + " cannot be null");
						}
						addCriterion(condition, new java.sql.Date(value.getTime()), property);
				}

				protected void addCriterionForJDBCDate (String condition, List<Date> values, String property) {
						if (values == null || values.size() == 0) {
								throw new RuntimeException("Value list for " + property + " cannot be null or empty");
						}
						List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
						Iterator<Date> iter = values.iterator();
						while (iter.hasNext()) {
								dateList.add(new java.sql.Date(iter.next().getTime()));
						}
						addCriterion(condition, dateList, property);
				}

				protected void addCriterionForJDBCDate (String condition, Date value1, Date value2, String property) {
						if (value1 == null || value2 == null) {
								throw new RuntimeException("Between values for " + property + " cannot be null");
						}
						addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
				}

				public Criteria andBook_nameIsNull () {
						addCriterion("book_name is null");
						return (Criteria) this;
				}

				public Criteria andBook_nameIsNotNull () {
						addCriterion("book_name is not null");
						return (Criteria) this;
				}

				public Criteria andBook_nameEqualTo (String value) {
						addCriterion("book_name =", value, "book_name");
						return (Criteria) this;
				}

				public Criteria andBook_nameNotEqualTo (String value) {
						addCriterion("book_name <>", value, "book_name");
						return (Criteria) this;
				}

				public Criteria andBook_nameGreaterThan (String value) {
						addCriterion("book_name >", value, "book_name");
						return (Criteria) this;
				}

				public Criteria andBook_nameGreaterThanOrEqualTo (String value) {
						addCriterion("book_name >=", value, "book_name");
						return (Criteria) this;
				}

				public Criteria andBook_nameLessThan (String value) {
						addCriterion("book_name <", value, "book_name");
						return (Criteria) this;
				}

				public Criteria andBook_nameLessThanOrEqualTo (String value) {
						addCriterion("book_name <=", value, "book_name");
						return (Criteria) this;
				}

				public Criteria andBook_nameLike (String value) {
						addCriterion("book_name like", value, "book_name");
						return (Criteria) this;
				}

				public Criteria andBook_nameNotLike (String value) {
						addCriterion("book_name not like", value, "book_name");
						return (Criteria) this;
				}

				public Criteria andBook_nameIn (List<String> values) {
						addCriterion("book_name in", values, "book_name");
						return (Criteria) this;
				}

				public Criteria andBook_nameNotIn (List<String> values) {
						addCriterion("book_name not in", values, "book_name");
						return (Criteria) this;
				}

				public Criteria andBook_nameBetween (String value1, String value2) {
						addCriterion("book_name between", value1, value2, "book_name");
						return (Criteria) this;
				}

				public Criteria andBook_nameNotBetween (String value1, String value2) {
						addCriterion("book_name not between", value1, value2, "book_name");
						return (Criteria) this;
				}

				public Criteria andBook_typeIsNull () {
						addCriterion("book_type is null");
						return (Criteria) this;
				}

				public Criteria andBook_typeIsNotNull () {
						addCriterion("book_type is not null");
						return (Criteria) this;
				}

				public Criteria andBook_typeEqualTo (String value) {
						addCriterion("book_type =", value, "book_type");
						return (Criteria) this;
				}

				public Criteria andBook_typeNotEqualTo (String value) {
						addCriterion("book_type <>", value, "book_type");
						return (Criteria) this;
				}

				public Criteria andBook_typeGreaterThan (String value) {
						addCriterion("book_type >", value, "book_type");
						return (Criteria) this;
				}

				public Criteria andBook_typeGreaterThanOrEqualTo (String value) {
						addCriterion("book_type >=", value, "book_type");
						return (Criteria) this;
				}

				public Criteria andBook_typeLessThan (String value) {
						addCriterion("book_type <", value, "book_type");
						return (Criteria) this;
				}

				public Criteria andBook_typeLessThanOrEqualTo (String value) {
						addCriterion("book_type <=", value, "book_type");
						return (Criteria) this;
				}

				public Criteria andBook_typeLike (String value) {
						addCriterion("book_type like", value, "book_type");
						return (Criteria) this;
				}

				public Criteria andBook_typeNotLike (String value) {
						addCriterion("book_type not like", value, "book_type");
						return (Criteria) this;
				}

				public Criteria andBook_typeIn (List<String> values) {
						addCriterion("book_type in", values, "book_type");
						return (Criteria) this;
				}

				public Criteria andBook_typeNotIn (List<String> values) {
						addCriterion("book_type not in", values, "book_type");
						return (Criteria) this;
				}

				public Criteria andBook_typeBetween (String value1, String value2) {
						addCriterion("book_type between", value1, value2, "book_type");
						return (Criteria) this;
				}

				public Criteria andBook_typeNotBetween (String value1, String value2) {
						addCriterion("book_type not between", value1, value2, "book_type");
						return (Criteria) this;
				}

				public Criteria andBook_authorIsNull () {
						addCriterion("book_author is null");
						return (Criteria) this;
				}

				public Criteria andBook_authorIsNotNull () {
						addCriterion("book_author is not null");
						return (Criteria) this;
				}

				public Criteria andBook_authorEqualTo (String value) {
						addCriterion("book_author =", value, "book_author");
						return (Criteria) this;
				}

				public Criteria andBook_authorNotEqualTo (String value) {
						addCriterion("book_author <>", value, "book_author");
						return (Criteria) this;
				}

				public Criteria andBook_authorGreaterThan (String value) {
						addCriterion("book_author >", value, "book_author");
						return (Criteria) this;
				}

				public Criteria andBook_authorGreaterThanOrEqualTo (String value) {
						addCriterion("book_author >=", value, "book_author");
						return (Criteria) this;
				}

				public Criteria andBook_authorLessThan (String value) {
						addCriterion("book_author <", value, "book_author");
						return (Criteria) this;
				}

				public Criteria andBook_authorLessThanOrEqualTo (String value) {
						addCriterion("book_author <=", value, "book_author");
						return (Criteria) this;
				}

				public Criteria andBook_authorLike (String value) {
						addCriterion("book_author like", value, "book_author");
						return (Criteria) this;
				}

				public Criteria andBook_authorNotLike (String value) {
						addCriterion("book_author not like", value, "book_author");
						return (Criteria) this;
				}

				public Criteria andBook_authorIn (List<String> values) {
						addCriterion("book_author in", values, "book_author");
						return (Criteria) this;
				}

				public Criteria andBook_authorNotIn (List<String> values) {
						addCriterion("book_author not in", values, "book_author");
						return (Criteria) this;
				}

				public Criteria andBook_authorBetween (String value1, String value2) {
						addCriterion("book_author between", value1, value2, "book_author");
						return (Criteria) this;
				}

				public Criteria andBook_authorNotBetween (String value1, String value2) {
						addCriterion("book_author not between", value1, value2, "book_author");
						return (Criteria) this;
				}

				public Criteria andBook_stateIsNull () {
						addCriterion("book_state is null");
						return (Criteria) this;
				}

				public Criteria andBook_stateIsNotNull () {
						addCriterion("book_state is not null");
						return (Criteria) this;
				}

				public Criteria andBook_stateEqualTo (String value) {
						addCriterion("book_state =", value, "book_state");
						return (Criteria) this;
				}

				public Criteria andBook_stateNotEqualTo (String value) {
						addCriterion("book_state <>", value, "book_state");
						return (Criteria) this;
				}

				public Criteria andBook_stateGreaterThan (String value) {
						addCriterion("book_state >", value, "book_state");
						return (Criteria) this;
				}

				public Criteria andBook_stateGreaterThanOrEqualTo (String value) {
						addCriterion("book_state >=", value, "book_state");
						return (Criteria) this;
				}

				public Criteria andBook_stateLessThan (String value) {
						addCriterion("book_state <", value, "book_state");
						return (Criteria) this;
				}

				public Criteria andBook_stateLessThanOrEqualTo (String value) {
						addCriterion("book_state <=", value, "book_state");
						return (Criteria) this;
				}

				public Criteria andBook_stateLike (String value) {
						addCriterion("book_state like", value, "book_state");
						return (Criteria) this;
				}

				public Criteria andBook_stateNotLike (String value) {
						addCriterion("book_state not like", value, "book_state");
						return (Criteria) this;
				}

				public Criteria andBook_stateIn (List<String> values) {
						addCriterion("book_state in", values, "book_state");
						return (Criteria) this;
				}

				public Criteria andBook_stateNotIn (List<String> values) {
						addCriterion("book_state not in", values, "book_state");
						return (Criteria) this;
				}

				public Criteria andBook_stateBetween (String value1, String value2) {
						addCriterion("book_state between", value1, value2, "book_state");
						return (Criteria) this;
				}

				public Criteria andBook_stateNotBetween (String value1, String value2) {
						addCriterion("book_state not between", value1, value2, "book_state");
						return (Criteria) this;
				}

				public Criteria andBook_wordsIsNull () {
						addCriterion("book_words is null");
						return (Criteria) this;
				}

				public Criteria andBook_wordsIsNotNull () {
						addCriterion("book_words is not null");
						return (Criteria) this;
				}

				public Criteria andBook_wordsEqualTo (Integer value) {
						addCriterion("book_words =", value, "book_words");
						return (Criteria) this;
				}

				public Criteria andBook_wordsNotEqualTo (Integer value) {
						addCriterion("book_words <>", value, "book_words");
						return (Criteria) this;
				}

				public Criteria andBook_wordsGreaterThan (Integer value) {
						addCriterion("book_words >", value, "book_words");
						return (Criteria) this;
				}

				public Criteria andBook_wordsGreaterThanOrEqualTo (Integer value) {
						addCriterion("book_words >=", value, "book_words");
						return (Criteria) this;
				}

				public Criteria andBook_wordsLessThan (Integer value) {
						addCriterion("book_words <", value, "book_words");
						return (Criteria) this;
				}

				public Criteria andBook_wordsLessThanOrEqualTo (Integer value) {
						addCriterion("book_words <=", value, "book_words");
						return (Criteria) this;
				}

				public Criteria andBook_wordsIn (List<Integer> values) {
						addCriterion("book_words in", values, "book_words");
						return (Criteria) this;
				}

				public Criteria andBook_wordsNotIn (List<Integer> values) {
						addCriterion("book_words not in", values, "book_words");
						return (Criteria) this;
				}

				public Criteria andBook_wordsBetween (Integer value1, Integer value2) {
						addCriterion("book_words between", value1, value2, "book_words");
						return (Criteria) this;
				}

				public Criteria andBook_wordsNotBetween (Integer value1, Integer value2) {
						addCriterion("book_words not between", value1, value2, "book_words");
						return (Criteria) this;
				}

				public Criteria andBook_introIsNull () {
						addCriterion("book_intro is null");
						return (Criteria) this;
				}

				public Criteria andBook_introIsNotNull () {
						addCriterion("book_intro is not null");
						return (Criteria) this;
				}

				public Criteria andBook_introEqualTo (String value) {
						addCriterion("book_intro =", value, "book_intro");
						return (Criteria) this;
				}

				public Criteria andBook_introNotEqualTo (String value) {
						addCriterion("book_intro <>", value, "book_intro");
						return (Criteria) this;
				}

				public Criteria andBook_introGreaterThan (String value) {
						addCriterion("book_intro >", value, "book_intro");
						return (Criteria) this;
				}

				public Criteria andBook_introGreaterThanOrEqualTo (String value) {
						addCriterion("book_intro >=", value, "book_intro");
						return (Criteria) this;
				}

				public Criteria andBook_introLessThan (String value) {
						addCriterion("book_intro <", value, "book_intro");
						return (Criteria) this;
				}

				public Criteria andBook_introLessThanOrEqualTo (String value) {
						addCriterion("book_intro <=", value, "book_intro");
						return (Criteria) this;
				}

				public Criteria andBook_introLike (String value) {
						addCriterion("book_intro like", value, "book_intro");
						return (Criteria) this;
				}

				public Criteria andBook_introNotLike (String value) {
						addCriterion("book_intro not like", value, "book_intro");
						return (Criteria) this;
				}

				public Criteria andBook_introIn (List<String> values) {
						addCriterion("book_intro in", values, "book_intro");
						return (Criteria) this;
				}

				public Criteria andBook_introNotIn (List<String> values) {
						addCriterion("book_intro not in", values, "book_intro");
						return (Criteria) this;
				}

				public Criteria andBook_introBetween (String value1, String value2) {
						addCriterion("book_intro between", value1, value2, "book_intro");
						return (Criteria) this;
				}

				public Criteria andBook_introNotBetween (String value1, String value2) {
						addCriterion("book_intro not between", value1, value2, "book_intro");
						return (Criteria) this;
				}

				public Criteria andBook_catalogIsNull () {
						addCriterion("book_catalog is null");
						return (Criteria) this;
				}

				public Criteria andBook_catalogIsNotNull () {
						addCriterion("book_catalog is not null");
						return (Criteria) this;
				}

				public Criteria andBook_catalogEqualTo (String value) {
						addCriterion("book_catalog =", value, "book_catalog");
						return (Criteria) this;
				}

				public Criteria andBook_catalogNotEqualTo (String value) {
						addCriterion("book_catalog <>", value, "book_catalog");
						return (Criteria) this;
				}

				public Criteria andBook_catalogGreaterThan (String value) {
						addCriterion("book_catalog >", value, "book_catalog");
						return (Criteria) this;
				}

				public Criteria andBook_catalogGreaterThanOrEqualTo (String value) {
						addCriterion("book_catalog >=", value, "book_catalog");
						return (Criteria) this;
				}

				public Criteria andBook_catalogLessThan (String value) {
						addCriterion("book_catalog <", value, "book_catalog");
						return (Criteria) this;
				}

				public Criteria andBook_catalogLessThanOrEqualTo (String value) {
						addCriterion("book_catalog <=", value, "book_catalog");
						return (Criteria) this;
				}

				public Criteria andBook_catalogLike (String value) {
						addCriterion("book_catalog like", value, "book_catalog");
						return (Criteria) this;
				}

				public Criteria andBook_catalogNotLike (String value) {
						addCriterion("book_catalog not like", value, "book_catalog");
						return (Criteria) this;
				}

				public Criteria andBook_catalogIn (List<String> values) {
						addCriterion("book_catalog in", values, "book_catalog");
						return (Criteria) this;
				}

				public Criteria andBook_catalogNotIn (List<String> values) {
						addCriterion("book_catalog not in", values, "book_catalog");
						return (Criteria) this;
				}

				public Criteria andBook_catalogBetween (String value1, String value2) {
						addCriterion("book_catalog between", value1, value2, "book_catalog");
						return (Criteria) this;
				}

				public Criteria andBook_catalogNotBetween (String value1, String value2) {
						addCriterion("book_catalog not between", value1, value2, "book_catalog");
						return (Criteria) this;
				}

				public Criteria andUpdate_timeIsNull () {
						addCriterion("update_time is null");
						return (Criteria) this;
				}

				public Criteria andUpdate_timeIsNotNull () {
						addCriterion("update_time is not null");
						return (Criteria) this;
				}

				public Criteria andUpdate_timeEqualTo (Date value) {
						addCriterionForJDBCDate("update_time =", value, "update_time");
						return (Criteria) this;
				}

				public Criteria andUpdate_timeNotEqualTo (Date value) {
						addCriterionForJDBCDate("update_time <>", value, "update_time");
						return (Criteria) this;
				}

				public Criteria andUpdate_timeGreaterThan (Date value) {
						addCriterionForJDBCDate("update_time >", value, "update_time");
						return (Criteria) this;
				}

				public Criteria andUpdate_timeGreaterThanOrEqualTo (Date value) {
						addCriterionForJDBCDate("update_time >=", value, "update_time");
						return (Criteria) this;
				}

				public Criteria andUpdate_timeLessThan (Date value) {
						addCriterionForJDBCDate("update_time <", value, "update_time");
						return (Criteria) this;
				}

				public Criteria andUpdate_timeLessThanOrEqualTo (Date value) {
						addCriterionForJDBCDate("update_time <=", value, "update_time");
						return (Criteria) this;
				}

				public Criteria andUpdate_timeIn (List<Date> values) {
						addCriterionForJDBCDate("update_time in", values, "update_time");
						return (Criteria) this;
				}

				public Criteria andUpdate_timeNotIn (List<Date> values) {
						addCriterionForJDBCDate("update_time not in", values, "update_time");
						return (Criteria) this;
				}

				public Criteria andUpdate_timeBetween (Date value1, Date value2) {
						addCriterionForJDBCDate("update_time between", value1, value2, "update_time");
						return (Criteria) this;
				}

				public Criteria andUpdate_timeNotBetween (Date value1, Date value2) {
						addCriterionForJDBCDate("update_time not between", value1, value2, "update_time");
						return (Criteria) this;
				}

				public Criteria andMonthly_ticketsIsNull () {
						addCriterion("monthly_tickets is null");
						return (Criteria) this;
				}

				public Criteria andMonthly_ticketsIsNotNull () {
						addCriterion("monthly_tickets is not null");
						return (Criteria) this;
				}

				public Criteria andMonthly_ticketsEqualTo (Integer value) {
						addCriterion("monthly_tickets =", value, "monthly_tickets");
						return (Criteria) this;
				}

				public Criteria andMonthly_ticketsNotEqualTo (Integer value) {
						addCriterion("monthly_tickets <>", value, "monthly_tickets");
						return (Criteria) this;
				}

				public Criteria andMonthly_ticketsGreaterThan (Integer value) {
						addCriterion("monthly_tickets >", value, "monthly_tickets");
						return (Criteria) this;
				}

				public Criteria andMonthly_ticketsGreaterThanOrEqualTo (Integer value) {
						addCriterion("monthly_tickets >=", value, "monthly_tickets");
						return (Criteria) this;
				}

				public Criteria andMonthly_ticketsLessThan (Integer value) {
						addCriterion("monthly_tickets <", value, "monthly_tickets");
						return (Criteria) this;
				}

				public Criteria andMonthly_ticketsLessThanOrEqualTo (Integer value) {
						addCriterion("monthly_tickets <=", value, "monthly_tickets");
						return (Criteria) this;
				}

				public Criteria andMonthly_ticketsIn (List<Integer> values) {
						addCriterion("monthly_tickets in", values, "monthly_tickets");
						return (Criteria) this;
				}

				public Criteria andMonthly_ticketsNotIn (List<Integer> values) {
						addCriterion("monthly_tickets not in", values, "monthly_tickets");
						return (Criteria) this;
				}

				public Criteria andMonthly_ticketsBetween (Integer value1, Integer value2) {
						addCriterion("monthly_tickets between", value1, value2, "monthly_tickets");
						return (Criteria) this;
				}

				public Criteria andMonthly_ticketsNotBetween (Integer value1, Integer value2) {
						addCriterion("monthly_tickets not between", value1, value2, "monthly_tickets");
						return (Criteria) this;
				}

				public Criteria andTotal_hitsIsNull () {
						addCriterion("total_hits is null");
						return (Criteria) this;
				}

				public Criteria andTotal_hitsIsNotNull () {
						addCriterion("total_hits is not null");
						return (Criteria) this;
				}

				public Criteria andTotal_hitsEqualTo (Integer value) {
						addCriterion("total_hits =", value, "total_hits");
						return (Criteria) this;
				}

				public Criteria andTotal_hitsNotEqualTo (Integer value) {
						addCriterion("total_hits <>", value, "total_hits");
						return (Criteria) this;
				}

				public Criteria andTotal_hitsGreaterThan (Integer value) {
						addCriterion("total_hits >", value, "total_hits");
						return (Criteria) this;
				}

				public Criteria andTotal_hitsGreaterThanOrEqualTo (Integer value) {
						addCriterion("total_hits >=", value, "total_hits");
						return (Criteria) this;
				}

				public Criteria andTotal_hitsLessThan (Integer value) {
						addCriterion("total_hits <", value, "total_hits");
						return (Criteria) this;
				}

				public Criteria andTotal_hitsLessThanOrEqualTo (Integer value) {
						addCriterion("total_hits <=", value, "total_hits");
						return (Criteria) this;
				}

				public Criteria andTotal_hitsIn (List<Integer> values) {
						addCriterion("total_hits in", values, "total_hits");
						return (Criteria) this;
				}

				public Criteria andTotal_hitsNotIn (List<Integer> values) {
						addCriterion("total_hits not in", values, "total_hits");
						return (Criteria) this;
				}

				public Criteria andTotal_hitsBetween (Integer value1, Integer value2) {
						addCriterion("total_hits between", value1, value2, "total_hits");
						return (Criteria) this;
				}

				public Criteria andTotal_hitsNotBetween (Integer value1, Integer value2) {
						addCriterion("total_hits not between", value1, value2, "total_hits");
						return (Criteria) this;
				}

				public Criteria andMonthly_hitsIsNull () {
						addCriterion("monthly_hits is null");
						return (Criteria) this;
				}

				public Criteria andMonthly_hitsIsNotNull () {
						addCriterion("monthly_hits is not null");
						return (Criteria) this;
				}

				public Criteria andMonthly_hitsEqualTo (Integer value) {
						addCriterion("monthly_hits =", value, "monthly_hits");
						return (Criteria) this;
				}

				public Criteria andMonthly_hitsNotEqualTo (Integer value) {
						addCriterion("monthly_hits <>", value, "monthly_hits");
						return (Criteria) this;
				}

				public Criteria andMonthly_hitsGreaterThan (Integer value) {
						addCriterion("monthly_hits >", value, "monthly_hits");
						return (Criteria) this;
				}

				public Criteria andMonthly_hitsGreaterThanOrEqualTo (Integer value) {
						addCriterion("monthly_hits >=", value, "monthly_hits");
						return (Criteria) this;
				}

				public Criteria andMonthly_hitsLessThan (Integer value) {
						addCriterion("monthly_hits <", value, "monthly_hits");
						return (Criteria) this;
				}

				public Criteria andMonthly_hitsLessThanOrEqualTo (Integer value) {
						addCriterion("monthly_hits <=", value, "monthly_hits");
						return (Criteria) this;
				}

				public Criteria andMonthly_hitsIn (List<Integer> values) {
						addCriterion("monthly_hits in", values, "monthly_hits");
						return (Criteria) this;
				}

				public Criteria andMonthly_hitsNotIn (List<Integer> values) {
						addCriterion("monthly_hits not in", values, "monthly_hits");
						return (Criteria) this;
				}

				public Criteria andMonthly_hitsBetween (Integer value1, Integer value2) {
						addCriterion("monthly_hits between", value1, value2, "monthly_hits");
						return (Criteria) this;
				}

				public Criteria andMonthly_hitsNotBetween (Integer value1, Integer value2) {
						addCriterion("monthly_hits not between", value1, value2, "monthly_hits");
						return (Criteria) this;
				}

				public Criteria andWeekly_hitsIsNull () {
						addCriterion("weekly_hits is null");
						return (Criteria) this;
				}

				public Criteria andWeekly_hitsIsNotNull () {
						addCriterion("weekly_hits is not null");
						return (Criteria) this;
				}

				public Criteria andWeekly_hitsEqualTo (Integer value) {
						addCriterion("weekly_hits =", value, "weekly_hits");
						return (Criteria) this;
				}

				public Criteria andWeekly_hitsNotEqualTo (Integer value) {
						addCriterion("weekly_hits <>", value, "weekly_hits");
						return (Criteria) this;
				}

				public Criteria andWeekly_hitsGreaterThan (Integer value) {
						addCriterion("weekly_hits >", value, "weekly_hits");
						return (Criteria) this;
				}

				public Criteria andWeekly_hitsGreaterThanOrEqualTo (Integer value) {
						addCriterion("weekly_hits >=", value, "weekly_hits");
						return (Criteria) this;
				}

				public Criteria andWeekly_hitsLessThan (Integer value) {
						addCriterion("weekly_hits <", value, "weekly_hits");
						return (Criteria) this;
				}

				public Criteria andWeekly_hitsLessThanOrEqualTo (Integer value) {
						addCriterion("weekly_hits <=", value, "weekly_hits");
						return (Criteria) this;
				}

				public Criteria andWeekly_hitsIn (List<Integer> values) {
						addCriterion("weekly_hits in", values, "weekly_hits");
						return (Criteria) this;
				}

				public Criteria andWeekly_hitsNotIn (List<Integer> values) {
						addCriterion("weekly_hits not in", values, "weekly_hits");
						return (Criteria) this;
				}

				public Criteria andWeekly_hitsBetween (Integer value1, Integer value2) {
						addCriterion("weekly_hits between", value1, value2, "weekly_hits");
						return (Criteria) this;
				}

				public Criteria andWeekly_hitsNotBetween (Integer value1, Integer value2) {
						addCriterion("weekly_hits not between", value1, value2, "weekly_hits");
						return (Criteria) this;
				}

				public Criteria andDaily_hitsIsNull () {
						addCriterion("daily_hits is null");
						return (Criteria) this;
				}

				public Criteria andDaily_hitsIsNotNull () {
						addCriterion("daily_hits is not null");
						return (Criteria) this;
				}

				public Criteria andDaily_hitsEqualTo (Integer value) {
						addCriterion("daily_hits =", value, "daily_hits");
						return (Criteria) this;
				}

				public Criteria andDaily_hitsNotEqualTo (Integer value) {
						addCriterion("daily_hits <>", value, "daily_hits");
						return (Criteria) this;
				}

				public Criteria andDaily_hitsGreaterThan (Integer value) {
						addCriterion("daily_hits >", value, "daily_hits");
						return (Criteria) this;
				}

				public Criteria andDaily_hitsGreaterThanOrEqualTo (Integer value) {
						addCriterion("daily_hits >=", value, "daily_hits");
						return (Criteria) this;
				}

				public Criteria andDaily_hitsLessThan (Integer value) {
						addCriterion("daily_hits <", value, "daily_hits");
						return (Criteria) this;
				}

				public Criteria andDaily_hitsLessThanOrEqualTo (Integer value) {
						addCriterion("daily_hits <=", value, "daily_hits");
						return (Criteria) this;
				}

				public Criteria andDaily_hitsIn (List<Integer> values) {
						addCriterion("daily_hits in", values, "daily_hits");
						return (Criteria) this;
				}

				public Criteria andDaily_hitsNotIn (List<Integer> values) {
						addCriterion("daily_hits not in", values, "daily_hits");
						return (Criteria) this;
				}

				public Criteria andDaily_hitsBetween (Integer value1, Integer value2) {
						addCriterion("daily_hits between", value1, value2, "daily_hits");
						return (Criteria) this;
				}

				public Criteria andDaily_hitsNotBetween (Integer value1, Integer value2) {
						addCriterion("daily_hits not between", value1, value2, "daily_hits");
						return (Criteria) this;
				}

				public Criteria andTotal_collectionsIsNull () {
						addCriterion("total_collections is null");
						return (Criteria) this;
				}

				public Criteria andTotal_collectionsIsNotNull () {
						addCriterion("total_collections is not null");
						return (Criteria) this;
				}

				public Criteria andTotal_collectionsEqualTo (Integer value) {
						addCriterion("total_collections =", value, "total_collections");
						return (Criteria) this;
				}

				public Criteria andTotal_collectionsNotEqualTo (Integer value) {
						addCriterion("total_collections <>", value, "total_collections");
						return (Criteria) this;
				}

				public Criteria andTotal_collectionsGreaterThan (Integer value) {
						addCriterion("total_collections >", value, "total_collections");
						return (Criteria) this;
				}

				public Criteria andTotal_collectionsGreaterThanOrEqualTo (Integer value) {
						addCriterion("total_collections >=", value, "total_collections");
						return (Criteria) this;
				}

				public Criteria andTotal_collectionsLessThan (Integer value) {
						addCriterion("total_collections <", value, "total_collections");
						return (Criteria) this;
				}

				public Criteria andTotal_collectionsLessThanOrEqualTo (Integer value) {
						addCriterion("total_collections <=", value, "total_collections");
						return (Criteria) this;
				}

				public Criteria andTotal_collectionsIn (List<Integer> values) {
						addCriterion("total_collections in", values, "total_collections");
						return (Criteria) this;
				}

				public Criteria andTotal_collectionsNotIn (List<Integer> values) {
						addCriterion("total_collections not in", values, "total_collections");
						return (Criteria) this;
				}

				public Criteria andTotal_collectionsBetween (Integer value1, Integer value2) {
						addCriterion("total_collections between", value1, value2, "total_collections");
						return (Criteria) this;
				}

				public Criteria andTotal_collectionsNotBetween (Integer value1, Integer value2) {
						addCriterion("total_collections not between", value1, value2, "total_collections");
						return (Criteria) this;
				}

				public Criteria andMonthly_collectionsIsNull () {
						addCriterion("monthly_collections is null");
						return (Criteria) this;
				}

				public Criteria andMonthly_collectionsIsNotNull () {
						addCriterion("monthly_collections is not null");
						return (Criteria) this;
				}

				public Criteria andMonthly_collectionsEqualTo (Integer value) {
						addCriterion("monthly_collections =", value, "monthly_collections");
						return (Criteria) this;
				}

				public Criteria andMonthly_collectionsNotEqualTo (Integer value) {
						addCriterion("monthly_collections <>", value, "monthly_collections");
						return (Criteria) this;
				}

				public Criteria andMonthly_collectionsGreaterThan (Integer value) {
						addCriterion("monthly_collections >", value, "monthly_collections");
						return (Criteria) this;
				}

				public Criteria andMonthly_collectionsGreaterThanOrEqualTo (Integer value) {
						addCriterion("monthly_collections >=", value, "monthly_collections");
						return (Criteria) this;
				}

				public Criteria andMonthly_collectionsLessThan (Integer value) {
						addCriterion("monthly_collections <", value, "monthly_collections");
						return (Criteria) this;
				}

				public Criteria andMonthly_collectionsLessThanOrEqualTo (Integer value) {
						addCriterion("monthly_collections <=", value, "monthly_collections");
						return (Criteria) this;
				}

				public Criteria andMonthly_collectionsIn (List<Integer> values) {
						addCriterion("monthly_collections in", values, "monthly_collections");
						return (Criteria) this;
				}

				public Criteria andMonthly_collectionsNotIn (List<Integer> values) {
						addCriterion("monthly_collections not in", values, "monthly_collections");
						return (Criteria) this;
				}

				public Criteria andMonthly_collectionsBetween (Integer value1, Integer value2) {
						addCriterion("monthly_collections between", value1, value2, "monthly_collections");
						return (Criteria) this;
				}

				public Criteria andMonthly_collectionsNotBetween (Integer value1, Integer value2) {
						addCriterion("monthly_collections not between", value1, value2, "monthly_collections");
						return (Criteria) this;
				}

				public Criteria andWeekly_collectionsIsNull () {
						addCriterion("weekly_collections is null");
						return (Criteria) this;
				}

				public Criteria andWeekly_collectionsIsNotNull () {
						addCriterion("weekly_collections is not null");
						return (Criteria) this;
				}

				public Criteria andWeekly_collectionsEqualTo (Integer value) {
						addCriterion("weekly_collections =", value, "weekly_collections");
						return (Criteria) this;
				}

				public Criteria andWeekly_collectionsNotEqualTo (Integer value) {
						addCriterion("weekly_collections <>", value, "weekly_collections");
						return (Criteria) this;
				}

				public Criteria andWeekly_collectionsGreaterThan (Integer value) {
						addCriterion("weekly_collections >", value, "weekly_collections");
						return (Criteria) this;
				}

				public Criteria andWeekly_collectionsGreaterThanOrEqualTo (Integer value) {
						addCriterion("weekly_collections >=", value, "weekly_collections");
						return (Criteria) this;
				}

				public Criteria andWeekly_collectionsLessThan (Integer value) {
						addCriterion("weekly_collections <", value, "weekly_collections");
						return (Criteria) this;
				}

				public Criteria andWeekly_collectionsLessThanOrEqualTo (Integer value) {
						addCriterion("weekly_collections <=", value, "weekly_collections");
						return (Criteria) this;
				}

				public Criteria andWeekly_collectionsIn (List<Integer> values) {
						addCriterion("weekly_collections in", values, "weekly_collections");
						return (Criteria) this;
				}

				public Criteria andWeekly_collectionsNotIn (List<Integer> values) {
						addCriterion("weekly_collections not in", values, "weekly_collections");
						return (Criteria) this;
				}

				public Criteria andWeekly_collectionsBetween (Integer value1, Integer value2) {
						addCriterion("weekly_collections between", value1, value2, "weekly_collections");
						return (Criteria) this;
				}

				public Criteria andWeekly_collectionsNotBetween (Integer value1, Integer value2) {
						addCriterion("weekly_collections not between", value1, value2, "weekly_collections");
						return (Criteria) this;
				}

				public Criteria andDaily_collectionsIsNull () {
						addCriterion("daily_collections is null");
						return (Criteria) this;
				}

				public Criteria andDaily_collectionsIsNotNull () {
						addCriterion("daily_collections is not null");
						return (Criteria) this;
				}

				public Criteria andDaily_collectionsEqualTo (Integer value) {
						addCriterion("daily_collections =", value, "daily_collections");
						return (Criteria) this;
				}

				public Criteria andDaily_collectionsNotEqualTo (Integer value) {
						addCriterion("daily_collections <>", value, "daily_collections");
						return (Criteria) this;
				}

				public Criteria andDaily_collectionsGreaterThan (Integer value) {
						addCriterion("daily_collections >", value, "daily_collections");
						return (Criteria) this;
				}

				public Criteria andDaily_collectionsGreaterThanOrEqualTo (Integer value) {
						addCriterion("daily_collections >=", value, "daily_collections");
						return (Criteria) this;
				}

				public Criteria andDaily_collectionsLessThan (Integer value) {
						addCriterion("daily_collections <", value, "daily_collections");
						return (Criteria) this;
				}

				public Criteria andDaily_collectionsLessThanOrEqualTo (Integer value) {
						addCriterion("daily_collections <=", value, "daily_collections");
						return (Criteria) this;
				}

				public Criteria andDaily_collectionsIn (List<Integer> values) {
						addCriterion("daily_collections in", values, "daily_collections");
						return (Criteria) this;
				}

				public Criteria andDaily_collectionsNotIn (List<Integer> values) {
						addCriterion("daily_collections not in", values, "daily_collections");
						return (Criteria) this;
				}

				public Criteria andDaily_collectionsBetween (Integer value1, Integer value2) {
						addCriterion("daily_collections between", value1, value2, "daily_collections");
						return (Criteria) this;
				}

				public Criteria andDaily_collectionsNotBetween (Integer value1, Integer value2) {
						addCriterion("daily_collections not between", value1, value2, "daily_collections");
						return (Criteria) this;
				}

				public Criteria andDownloadsIsNull () {
						addCriterion("downloads is null");
						return (Criteria) this;
				}

				public Criteria andDownloadsIsNotNull () {
						addCriterion("downloads is not null");
						return (Criteria) this;
				}

				public Criteria andDownloadsEqualTo (Integer value) {
						addCriterion("downloads =", value, "downloads");
						return (Criteria) this;
				}

				public Criteria andDownloadsNotEqualTo (Integer value) {
						addCriterion("downloads <>", value, "downloads");
						return (Criteria) this;
				}

				public Criteria andDownloadsGreaterThan (Integer value) {
						addCriterion("downloads >", value, "downloads");
						return (Criteria) this;
				}

				public Criteria andDownloadsGreaterThanOrEqualTo (Integer value) {
						addCriterion("downloads >=", value, "downloads");
						return (Criteria) this;
				}

				public Criteria andDownloadsLessThan (Integer value) {
						addCriterion("downloads <", value, "downloads");
						return (Criteria) this;
				}

				public Criteria andDownloadsLessThanOrEqualTo (Integer value) {
						addCriterion("downloads <=", value, "downloads");
						return (Criteria) this;
				}

				public Criteria andDownloadsIn (List<Integer> values) {
						addCriterion("downloads in", values, "downloads");
						return (Criteria) this;
				}

				public Criteria andDownloadsNotIn (List<Integer> values) {
						addCriterion("downloads not in", values, "downloads");
						return (Criteria) this;
				}

				public Criteria andDownloadsBetween (Integer value1, Integer value2) {
						addCriterion("downloads between", value1, value2, "downloads");
						return (Criteria) this;
				}

				public Criteria andDownloadsNotBetween (Integer value1, Integer value2) {
						addCriterion("downloads not between", value1, value2, "downloads");
						return (Criteria) this;
				}

				public Criteria andCommentsIsNull () {
						addCriterion("comments is null");
						return (Criteria) this;
				}

				public Criteria andCommentsIsNotNull () {
						addCriterion("comments is not null");
						return (Criteria) this;
				}

				public Criteria andCommentsEqualTo (String value) {
						addCriterion("comments =", value, "comments");
						return (Criteria) this;
				}

				public Criteria andCommentsNotEqualTo (String value) {
						addCriterion("comments <>", value, "comments");
						return (Criteria) this;
				}

				public Criteria andCommentsGreaterThan (String value) {
						addCriterion("comments >", value, "comments");
						return (Criteria) this;
				}

				public Criteria andCommentsGreaterThanOrEqualTo (String value) {
						addCriterion("comments >=", value, "comments");
						return (Criteria) this;
				}

				public Criteria andCommentsLessThan (String value) {
						addCriterion("comments <", value, "comments");
						return (Criteria) this;
				}

				public Criteria andCommentsLessThanOrEqualTo (String value) {
						addCriterion("comments <=", value, "comments");
						return (Criteria) this;
				}

				public Criteria andCommentsLike (String value) {
						addCriterion("comments like", value, "comments");
						return (Criteria) this;
				}

				public Criteria andCommentsNotLike (String value) {
						addCriterion("comments not like", value, "comments");
						return (Criteria) this;
				}

				public Criteria andCommentsIn (List<String> values) {
						addCriterion("comments in", values, "comments");
						return (Criteria) this;
				}

				public Criteria andCommentsNotIn (List<String> values) {
						addCriterion("comments not in", values, "comments");
						return (Criteria) this;
				}

				public Criteria andCommentsBetween (String value1, String value2) {
						addCriterion("comments between", value1, value2, "comments");
						return (Criteria) this;
				}

				public Criteria andCommentsNotBetween (String value1, String value2) {
						addCriterion("comments not between", value1, value2, "comments");
						return (Criteria) this;
				}
		}

		/**
		 * This class was generated by MyBatis Generator.
		 * This class corresponds to the database table novel
		 *
		 * @mbg.generated do_not_delete_during_merge Sat Jun 06 19:29:15 CST 2020
		 */
		public static class Criteria extends GeneratedCriteria {

				protected Criteria () {
						super();
				}
		}

		/**
		 * This class was generated by MyBatis Generator.
		 * This class corresponds to the database table novel
		 *
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		public static class Criterion {
				private String condition;

				private Object value;

				private Object secondValue;

				private boolean noValue;

				private boolean singleValue;

				private boolean betweenValue;

				private boolean listValue;

				private String typeHandler;

				public String getCondition () {
						return condition;
				}

				public Object getValue () {
						return value;
				}

				public Object getSecondValue () {
						return secondValue;
				}

				public boolean isNoValue () {
						return noValue;
				}

				public boolean isSingleValue () {
						return singleValue;
				}

				public boolean isBetweenValue () {
						return betweenValue;
				}

				public boolean isListValue () {
						return listValue;
				}

				public String getTypeHandler () {
						return typeHandler;
				}

				protected Criterion (String condition) {
						super();
						this.condition = condition;
						this.typeHandler = null;
						this.noValue = true;
				}

				protected Criterion (String condition, Object value, String typeHandler) {
						super();
						this.condition = condition;
						this.value = value;
						this.typeHandler = typeHandler;
						if (value instanceof List<?>) {
								this.listValue = true;
						} else {
								this.singleValue = true;
						}
				}

				protected Criterion (String condition, Object value) {
						this(condition, value, null);
				}

				protected Criterion (String condition, Object value, Object secondValue, String typeHandler) {
						super();
						this.condition = condition;
						this.value = value;
						this.secondValue = secondValue;
						this.typeHandler = typeHandler;
						this.betweenValue = true;
				}

				protected Criterion (String condition, Object value, Object secondValue) {
						this(condition, value, secondValue, null);
				}
		}
}