package cn.xy.novelwebproject.bean;

public class Noveltype {
		/**
		 * This field was generated by MyBatis Generator.
		 * This field corresponds to the database column noveltype.id
		 *
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		private Integer id;

		/**
		 * This field was generated by MyBatis Generator.
		 * This field corresponds to the database column noveltype.typename
		 *
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		private String typename;

		/**
		 * This method was generated by MyBatis Generator.
		 * This method returns the value of the database column noveltype.id
		 *
		 * @return the value of noveltype.id
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		public Integer getId () {
				return id;
		}

		/**
		 * This method was generated by MyBatis Generator.
		 * This method sets the value of the database column noveltype.id
		 *
		 * @param id the value for noveltype.id
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		public void setId (Integer id) {
				this.id = id;
		}

		/**
		 * This method was generated by MyBatis Generator.
		 * This method returns the value of the database column noveltype.typename
		 *
		 * @return the value of noveltype.typename
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		public String getTypename () {
				return typename;
		}

		/**
		 * This method was generated by MyBatis Generator.
		 * This method sets the value of the database column noveltype.typename
		 *
		 * @param typename the value for noveltype.typename
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		public void setTypename (String typename) {
				this.typename = typename == null ? null : typename.trim();
		}

		@Override
		public String toString () {
				return "Noveltype{" +
						"id=" + id +
						", typename='" + typename + '\'' +
						'}';
		}
}