package cn.xy.novelwebproject.bean;

import java.util.Arrays;
import java.util.Date;
import java.util.List;

public class Reader {
		/**
		 * This field was generated by MyBatis Generator.
		 * This field corresponds to the database column readers.nick_name
		 *
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		private String nick_name;

		/**
		 * This field was generated by MyBatis Generator.
		 * This field corresponds to the database column readers.sex
		 *
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		private String sex;

		/**
		 * This field was generated by MyBatis Generator.
		 * This field corresponds to the database column readers.birthday
		 *
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		private Date birthday;
		private String birth;
		/**
		 * This field was generated by MyBatis Generator.
		 * This field corresponds to the database column readers.intro
		 *
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		private String intro;

		/**
		 * This field was generated by MyBatis Generator.
		 * This field corresponds to the database column readers.address
		 *
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		private String address;

		/**
		 * This field was generated by MyBatis Generator.
		 * This field corresponds to the database column readers.fans
		 *
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		private Integer fans;

		/**
		 * This field was generated by MyBatis Generator.
		 * This field corresponds to the database column readers.mybookshelf
		 *
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		private List<NovelShelf> mybookshelf;

		/**
		 * This field was generated by MyBatis Generator.
		 * This field corresponds to the database column readers.collection_novels
		 *
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		private List<Novel> collection_novels;

		/**
		 * This field was generated by MyBatis Generator.
		 * This field corresponds to the database column readers.subscribed_novels
		 *
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		private List<Novel> subscribed_novels;

		/**
		 * This field was generated by MyBatis Generator.
		 * This field corresponds to the database column readers.footmark
		 *
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		private List<Novel> footmark;

		/**
		 * This field was generated by MyBatis Generator.
		 * This field corresponds to the database column readers.account_balance
		 *
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		private Integer account_balance;

		/**
		 * This field was generated by MyBatis Generator.
		 * This field corresponds to the database column readers.monthly_tickets
		 *
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		private Integer monthly_tickets;

		/**
		 * This field was generated by MyBatis Generator.
		 * This field corresponds to the database column readers.mycomments
		 *
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		private Comment[] mycomments;

		/**
		 * This field was generated by MyBatis Generator.
		 * This field corresponds to the database column readers.vip
		 *
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		private Integer vip;

		/**
		 * This field was generated by MyBatis Generator.
		 * This field corresponds to the database column readers.access
		 *
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		private String access;

		private String password;

		private String headimage;

		public String getBirth() {
				return birth;
		}

		public void setBirth(String birth) {
				this.birth = birth;
		}

		public String getHeadimage() {
				return headimage;
		}

		public void setHeadimage(String headimage) {
				this.headimage = headimage;
		}

		public String getPassword () {
				return password;
		}

		public void setPassword (String password) {
				this.password = password;
		}

		public String getNick_name () {
				return nick_name;
		}

		public void setNick_name (String nick_name) {
				this.nick_name = nick_name;
		}

		public String getSex () {
				return sex;
		}

		public void setSex (String sex) {
				this.sex = sex;
		}

		public Date getBirthday () {
				return birthday;
		}

		public void setBirthday (Date birthday) {
				this.birthday = birthday;
		}

		public String getIntro () {
				return intro;
		}

		public void setIntro (String intro) {
				this.intro = intro;
		}

		public String getAddress () {
				return address;
		}

		public void setAddress (String address) {
				this.address = address;
		}

		public Integer getFans () {
				return fans;
		}

		public void setFans (Integer fans) {
				this.fans = fans;
		}

		public List<NovelShelf> getMybookshelf() {
				return mybookshelf;
		}

		public void setMybookshelf(List<NovelShelf> mybookshelf) {
				this.mybookshelf = mybookshelf;
		}

		public List<Novel> getCollection_novels() {
				return collection_novels;
		}

		public void setCollection_novels(List<Novel> collection_novels) {
				this.collection_novels = collection_novels;
		}

		public List<Novel> getSubscribed_novels() {
				return subscribed_novels;
		}

		public void setSubscribed_novels(List<Novel> subscribed_novels) {
				this.subscribed_novels = subscribed_novels;
		}

		public List<Novel> getFootmark() {
				return footmark;
		}

		public void setFootmark(List<Novel> footmark) {
				this.footmark = footmark;
		}

		public Integer getAccount_balance() {
				return account_balance;
		}

		public void setAccount_balance(Integer account_balance) {
				this.account_balance = account_balance;
		}

		public Integer getMonthly_tickets() {
				return monthly_tickets;
		}

		public void setMonthly_tickets(Integer monthly_tickets) {
				this.monthly_tickets = monthly_tickets;
		}

		public Comment[] getMycomments() {
				return mycomments;
		}

		public void setMycomments(Comment[] mycomments) {
				this.mycomments = mycomments;
		}

		public Integer getVip() {
				return vip;
		}

		public void setVip(Integer vip) {
				this.vip = vip;
		}

		public String getAccess() {
				return access;
		}

		public void setAccess(String access) {
				this.access = access;
		}

		@Override
		public String toString() {
				return "Reader{" +
					"nick_name='" + nick_name + '\'' +
					", sex='" + sex + '\'' +
					", birthday=" + birthday +
					", birth='" + birth + '\'' +
					", intro='" + intro + '\'' +
					", address='" + address + '\'' +
					", fans=" + fans +
					", mybookshelf=" + mybookshelf +
					", collection_novels=" + collection_novels +
					", subscribed_novels=" + subscribed_novels +
					", footmark=" + footmark +
					", account_balance=" + account_balance +
					", monthly_tickets=" + monthly_tickets +
					", mycomments=" + Arrays.toString(mycomments) +
					", vip=" + vip +
					", access='" + access + '\'' +
					", password='" + password + '\'' +
					", headimage='" + headimage + '\'' +
					'}';
		}
}