package cn.xy.novelwebproject.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class ReaderExample {
		/**
		 * This field was generated by MyBatis Generator.
		 * This field corresponds to the database table readers
		 *
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		protected String orderByClause;

		/**
		 * This field was generated by MyBatis Generator.
		 * This field corresponds to the database table readers
		 *
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		protected boolean distinct;

		/**
		 * This field was generated by MyBatis Generator.
		 * This field corresponds to the database table readers
		 *
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		protected List<Criteria> oredCriteria;

		/**
		 * This method was generated by MyBatis Generator.
		 * This method corresponds to the database table readers
		 *
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		public ReaderExample () {
				oredCriteria = new ArrayList<Criteria>();
		}

		/**
		 * This method was generated by MyBatis Generator.
		 * This method corresponds to the database table readers
		 *
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		public void setOrderByClause (String orderByClause) {
				this.orderByClause = orderByClause;
		}

		/**
		 * This method was generated by MyBatis Generator.
		 * This method corresponds to the database table readers
		 *
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		public String getOrderByClause () {
				return orderByClause;
		}

		/**
		 * This method was generated by MyBatis Generator.
		 * This method corresponds to the database table readers
		 *
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		public void setDistinct (boolean distinct) {
				this.distinct = distinct;
		}

		/**
		 * This method was generated by MyBatis Generator.
		 * This method corresponds to the database table readers
		 *
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		public boolean isDistinct () {
				return distinct;
		}

		/**
		 * This method was generated by MyBatis Generator.
		 * This method corresponds to the database table readers
		 *
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		public List<Criteria> getOredCriteria () {
				return oredCriteria;
		}

		/**
		 * This method was generated by MyBatis Generator.
		 * This method corresponds to the database table readers
		 *
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		public void or (Criteria criteria) {
				oredCriteria.add(criteria);
		}

		/**
		 * This method was generated by MyBatis Generator.
		 * This method corresponds to the database table readers
		 *
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		public Criteria or () {
				Criteria criteria = createCriteriaInternal();
				oredCriteria.add(criteria);
				return criteria;
		}

		/**
		 * This method was generated by MyBatis Generator.
		 * This method corresponds to the database table readers
		 *
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		public Criteria createCriteria () {
				Criteria criteria = createCriteriaInternal();
				if (oredCriteria.size() == 0) {
						oredCriteria.add(criteria);
				}
				return criteria;
		}

		/**
		 * This method was generated by MyBatis Generator.
		 * This method corresponds to the database table readers
		 *
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		protected Criteria createCriteriaInternal () {
				Criteria criteria = new Criteria();
				return criteria;
		}

		/**
		 * This method was generated by MyBatis Generator.
		 * This method corresponds to the database table readers
		 *
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		public void clear () {
				oredCriteria.clear();
				orderByClause = null;
				distinct = false;
		}

		/**
		 * This class was generated by MyBatis Generator.
		 * This class corresponds to the database table readers
		 *
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		protected abstract static class GeneratedCriteria {
				protected List<Criterion> criteria;

				protected GeneratedCriteria () {
						super();
						criteria = new ArrayList<Criterion>();
				}

				public boolean isValid () {
						return criteria.size() > 0;
				}

				public List<Criterion> getAllCriteria () {
						return criteria;
				}

				public List<Criterion> getCriteria () {
						return criteria;
				}

				protected void addCriterion (String condition) {
						if (condition == null) {
								throw new RuntimeException("Value for condition cannot be null");
						}
						criteria.add(new Criterion(condition));
				}

				protected void addCriterion (String condition, Object value, String property) {
						if (value == null) {
								throw new RuntimeException("Value for " + property + " cannot be null");
						}
						criteria.add(new Criterion(condition, value));
				}

				protected void addCriterion (String condition, Object value1, Object value2, String property) {
						if (value1 == null || value2 == null) {
								throw new RuntimeException("Between values for " + property + " cannot be null");
						}
						criteria.add(new Criterion(condition, value1, value2));
				}

				protected void addCriterionForJDBCDate (String condition, Date value, String property) {
						if (value == null) {
								throw new RuntimeException("Value for " + property + " cannot be null");
						}
						addCriterion(condition, new java.sql.Date(value.getTime()), property);
				}

				protected void addCriterionForJDBCDate (String condition, List<Date> values, String property) {
						if (values == null || values.size() == 0) {
								throw new RuntimeException("Value list for " + property + " cannot be null or empty");
						}
						List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
						Iterator<Date> iter = values.iterator();
						while (iter.hasNext()) {
								dateList.add(new java.sql.Date(iter.next().getTime()));
						}
						addCriterion(condition, dateList, property);
				}

				protected void addCriterionForJDBCDate (String condition, Date value1, Date value2, String property) {
						if (value1 == null || value2 == null) {
								throw new RuntimeException("Between values for " + property + " cannot be null");
						}
						addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
				}

				public Criteria andNick_nameIsNull () {
						addCriterion("nick_name is null");
						return (Criteria) this;
				}

				public Criteria andNick_nameIsNotNull () {
						addCriterion("nick_name is not null");
						return (Criteria) this;
				}

				public Criteria andNick_nameEqualTo (String value) {
						addCriterion("nick_name =", value, "nick_name");
						return (Criteria) this;
				}

				public Criteria andNick_nameNotEqualTo (String value) {
						addCriterion("nick_name <>", value, "nick_name");
						return (Criteria) this;
				}

				public Criteria andNick_nameGreaterThan (String value) {
						addCriterion("nick_name >", value, "nick_name");
						return (Criteria) this;
				}

				public Criteria andNick_nameGreaterThanOrEqualTo (String value) {
						addCriterion("nick_name >=", value, "nick_name");
						return (Criteria) this;
				}

				public Criteria andNick_nameLessThan (String value) {
						addCriterion("nick_name <", value, "nick_name");
						return (Criteria) this;
				}

				public Criteria andNick_nameLessThanOrEqualTo (String value) {
						addCriterion("nick_name <=", value, "nick_name");
						return (Criteria) this;
				}

				public Criteria andNick_nameLike (String value) {
						addCriterion("nick_name like", value, "nick_name");
						return (Criteria) this;
				}

				public Criteria andNick_nameNotLike (String value) {
						addCriterion("nick_name not like", value, "nick_name");
						return (Criteria) this;
				}

				public Criteria andNick_nameIn (List<String> values) {
						addCriterion("nick_name in", values, "nick_name");
						return (Criteria) this;
				}

				public Criteria andNick_nameNotIn (List<String> values) {
						addCriterion("nick_name not in", values, "nick_name");
						return (Criteria) this;
				}

				public Criteria andNick_nameBetween (String value1, String value2) {
						addCriterion("nick_name between", value1, value2, "nick_name");
						return (Criteria) this;
				}

				public Criteria andNick_nameNotBetween (String value1, String value2) {
						addCriterion("nick_name not between", value1, value2, "nick_name");
						return (Criteria) this;
				}

				public Criteria andSexIsNull () {
						addCriterion("sex is null");
						return (Criteria) this;
				}

				public Criteria andSexIsNotNull () {
						addCriterion("sex is not null");
						return (Criteria) this;
				}

				public Criteria andSexEqualTo (String value) {
						addCriterion("sex =", value, "sex");
						return (Criteria) this;
				}

				public Criteria andSexNotEqualTo (String value) {
						addCriterion("sex <>", value, "sex");
						return (Criteria) this;
				}

				public Criteria andSexGreaterThan (String value) {
						addCriterion("sex >", value, "sex");
						return (Criteria) this;
				}

				public Criteria andSexGreaterThanOrEqualTo (String value) {
						addCriterion("sex >=", value, "sex");
						return (Criteria) this;
				}

				public Criteria andSexLessThan (String value) {
						addCriterion("sex <", value, "sex");
						return (Criteria) this;
				}

				public Criteria andSexLessThanOrEqualTo (String value) {
						addCriterion("sex <=", value, "sex");
						return (Criteria) this;
				}

				public Criteria andSexLike (String value) {
						addCriterion("sex like", value, "sex");
						return (Criteria) this;
				}

				public Criteria andSexNotLike (String value) {
						addCriterion("sex not like", value, "sex");
						return (Criteria) this;
				}

				public Criteria andSexIn (List<String> values) {
						addCriterion("sex in", values, "sex");
						return (Criteria) this;
				}

				public Criteria andSexNotIn (List<String> values) {
						addCriterion("sex not in", values, "sex");
						return (Criteria) this;
				}

				public Criteria andSexBetween (String value1, String value2) {
						addCriterion("sex between", value1, value2, "sex");
						return (Criteria) this;
				}

				public Criteria andSexNotBetween (String value1, String value2) {
						addCriterion("sex not between", value1, value2, "sex");
						return (Criteria) this;
				}

				public Criteria andBirthdayIsNull () {
						addCriterion("birthday is null");
						return (Criteria) this;
				}

				public Criteria andBirthdayIsNotNull () {
						addCriterion("birthday is not null");
						return (Criteria) this;
				}

				public Criteria andBirthdayEqualTo (Date value) {
						addCriterionForJDBCDate("birthday =", value, "birthday");
						return (Criteria) this;
				}

				public Criteria andBirthdayNotEqualTo (Date value) {
						addCriterionForJDBCDate("birthday <>", value, "birthday");
						return (Criteria) this;
				}

				public Criteria andBirthdayGreaterThan (Date value) {
						addCriterionForJDBCDate("birthday >", value, "birthday");
						return (Criteria) this;
				}

				public Criteria andBirthdayGreaterThanOrEqualTo (Date value) {
						addCriterionForJDBCDate("birthday >=", value, "birthday");
						return (Criteria) this;
				}

				public Criteria andBirthdayLessThan (Date value) {
						addCriterionForJDBCDate("birthday <", value, "birthday");
						return (Criteria) this;
				}

				public Criteria andBirthdayLessThanOrEqualTo (Date value) {
						addCriterionForJDBCDate("birthday <=", value, "birthday");
						return (Criteria) this;
				}

				public Criteria andBirthdayIn (List<Date> values) {
						addCriterionForJDBCDate("birthday in", values, "birthday");
						return (Criteria) this;
				}

				public Criteria andBirthdayNotIn (List<Date> values) {
						addCriterionForJDBCDate("birthday not in", values, "birthday");
						return (Criteria) this;
				}

				public Criteria andBirthdayBetween (Date value1, Date value2) {
						addCriterionForJDBCDate("birthday between", value1, value2, "birthday");
						return (Criteria) this;
				}

				public Criteria andBirthdayNotBetween (Date value1, Date value2) {
						addCriterionForJDBCDate("birthday not between", value1, value2, "birthday");
						return (Criteria) this;
				}

				public Criteria andIntroIsNull () {
						addCriterion("intro is null");
						return (Criteria) this;
				}

				public Criteria andIntroIsNotNull () {
						addCriterion("intro is not null");
						return (Criteria) this;
				}

				public Criteria andIntroEqualTo (String value) {
						addCriterion("intro =", value, "intro");
						return (Criteria) this;
				}

				public Criteria andIntroNotEqualTo (String value) {
						addCriterion("intro <>", value, "intro");
						return (Criteria) this;
				}

				public Criteria andIntroGreaterThan (String value) {
						addCriterion("intro >", value, "intro");
						return (Criteria) this;
				}

				public Criteria andIntroGreaterThanOrEqualTo (String value) {
						addCriterion("intro >=", value, "intro");
						return (Criteria) this;
				}

				public Criteria andIntroLessThan (String value) {
						addCriterion("intro <", value, "intro");
						return (Criteria) this;
				}

				public Criteria andIntroLessThanOrEqualTo (String value) {
						addCriterion("intro <=", value, "intro");
						return (Criteria) this;
				}

				public Criteria andIntroLike (String value) {
						addCriterion("intro like", value, "intro");
						return (Criteria) this;
				}

				public Criteria andIntroNotLike (String value) {
						addCriterion("intro not like", value, "intro");
						return (Criteria) this;
				}

				public Criteria andIntroIn (List<String> values) {
						addCriterion("intro in", values, "intro");
						return (Criteria) this;
				}

				public Criteria andIntroNotIn (List<String> values) {
						addCriterion("intro not in", values, "intro");
						return (Criteria) this;
				}

				public Criteria andIntroBetween (String value1, String value2) {
						addCriterion("intro between", value1, value2, "intro");
						return (Criteria) this;
				}

				public Criteria andIntroNotBetween (String value1, String value2) {
						addCriterion("intro not between", value1, value2, "intro");
						return (Criteria) this;
				}

				public Criteria andAddressIsNull () {
						addCriterion("address is null");
						return (Criteria) this;
				}

				public Criteria andAddressIsNotNull () {
						addCriterion("address is not null");
						return (Criteria) this;
				}

				public Criteria andAddressEqualTo (String value) {
						addCriterion("address =", value, "address");
						return (Criteria) this;
				}

				public Criteria andAddressNotEqualTo (String value) {
						addCriterion("address <>", value, "address");
						return (Criteria) this;
				}

				public Criteria andAddressGreaterThan (String value) {
						addCriterion("address >", value, "address");
						return (Criteria) this;
				}

				public Criteria andAddressGreaterThanOrEqualTo (String value) {
						addCriterion("address >=", value, "address");
						return (Criteria) this;
				}

				public Criteria andAddressLessThan (String value) {
						addCriterion("address <", value, "address");
						return (Criteria) this;
				}

				public Criteria andAddressLessThanOrEqualTo (String value) {
						addCriterion("address <=", value, "address");
						return (Criteria) this;
				}

				public Criteria andAddressLike (String value) {
						addCriterion("address like", value, "address");
						return (Criteria) this;
				}

				public Criteria andAddressNotLike (String value) {
						addCriterion("address not like", value, "address");
						return (Criteria) this;
				}

				public Criteria andAddressIn (List<String> values) {
						addCriterion("address in", values, "address");
						return (Criteria) this;
				}

				public Criteria andAddressNotIn (List<String> values) {
						addCriterion("address not in", values, "address");
						return (Criteria) this;
				}

				public Criteria andAddressBetween (String value1, String value2) {
						addCriterion("address between", value1, value2, "address");
						return (Criteria) this;
				}

				public Criteria andAddressNotBetween (String value1, String value2) {
						addCriterion("address not between", value1, value2, "address");
						return (Criteria) this;
				}

				public Criteria andFansIsNull () {
						addCriterion("fans is null");
						return (Criteria) this;
				}

				public Criteria andFansIsNotNull () {
						addCriterion("fans is not null");
						return (Criteria) this;
				}

				public Criteria andFansEqualTo (Integer value) {
						addCriterion("fans =", value, "fans");
						return (Criteria) this;
				}

				public Criteria andFansNotEqualTo (Integer value) {
						addCriterion("fans <>", value, "fans");
						return (Criteria) this;
				}

				public Criteria andFansGreaterThan (Integer value) {
						addCriterion("fans >", value, "fans");
						return (Criteria) this;
				}

				public Criteria andFansGreaterThanOrEqualTo (Integer value) {
						addCriterion("fans >=", value, "fans");
						return (Criteria) this;
				}

				public Criteria andFansLessThan (Integer value) {
						addCriterion("fans <", value, "fans");
						return (Criteria) this;
				}

				public Criteria andFansLessThanOrEqualTo (Integer value) {
						addCriterion("fans <=", value, "fans");
						return (Criteria) this;
				}

				public Criteria andFansIn (List<Integer> values) {
						addCriterion("fans in", values, "fans");
						return (Criteria) this;
				}

				public Criteria andFansNotIn (List<Integer> values) {
						addCriterion("fans not in", values, "fans");
						return (Criteria) this;
				}

				public Criteria andFansBetween (Integer value1, Integer value2) {
						addCriterion("fans between", value1, value2, "fans");
						return (Criteria) this;
				}

				public Criteria andFansNotBetween (Integer value1, Integer value2) {
						addCriterion("fans not between", value1, value2, "fans");
						return (Criteria) this;
				}

				public Criteria andMybookshelfIsNull () {
						addCriterion("mybookshelf is null");
						return (Criteria) this;
				}

				public Criteria andMybookshelfIsNotNull () {
						addCriterion("mybookshelf is not null");
						return (Criteria) this;
				}

				public Criteria andMybookshelfEqualTo (String value) {
						addCriterion("mybookshelf =", value, "mybookshelf");
						return (Criteria) this;
				}

				public Criteria andMybookshelfNotEqualTo (String value) {
						addCriterion("mybookshelf <>", value, "mybookshelf");
						return (Criteria) this;
				}

				public Criteria andMybookshelfGreaterThan (String value) {
						addCriterion("mybookshelf >", value, "mybookshelf");
						return (Criteria) this;
				}

				public Criteria andMybookshelfGreaterThanOrEqualTo (String value) {
						addCriterion("mybookshelf >=", value, "mybookshelf");
						return (Criteria) this;
				}

				public Criteria andMybookshelfLessThan (String value) {
						addCriterion("mybookshelf <", value, "mybookshelf");
						return (Criteria) this;
				}

				public Criteria andMybookshelfLessThanOrEqualTo (String value) {
						addCriterion("mybookshelf <=", value, "mybookshelf");
						return (Criteria) this;
				}

				public Criteria andMybookshelfLike (String value) {
						addCriterion("mybookshelf like", value, "mybookshelf");
						return (Criteria) this;
				}

				public Criteria andMybookshelfNotLike (String value) {
						addCriterion("mybookshelf not like", value, "mybookshelf");
						return (Criteria) this;
				}

				public Criteria andMybookshelfIn (List<String> values) {
						addCriterion("mybookshelf in", values, "mybookshelf");
						return (Criteria) this;
				}

				public Criteria andMybookshelfNotIn (List<String> values) {
						addCriterion("mybookshelf not in", values, "mybookshelf");
						return (Criteria) this;
				}

				public Criteria andMybookshelfBetween (String value1, String value2) {
						addCriterion("mybookshelf between", value1, value2, "mybookshelf");
						return (Criteria) this;
				}

				public Criteria andMybookshelfNotBetween (String value1, String value2) {
						addCriterion("mybookshelf not between", value1, value2, "mybookshelf");
						return (Criteria) this;
				}

				public Criteria andCollection_novelsIsNull () {
						addCriterion("collection_novels is null");
						return (Criteria) this;
				}

				public Criteria andCollection_novelsIsNotNull () {
						addCriterion("collection_novels is not null");
						return (Criteria) this;
				}

				public Criteria andCollection_novelsEqualTo (String value) {
						addCriterion("collection_novels =", value, "collection_novels");
						return (Criteria) this;
				}

				public Criteria andCollection_novelsNotEqualTo (String value) {
						addCriterion("collection_novels <>", value, "collection_novels");
						return (Criteria) this;
				}

				public Criteria andCollection_novelsGreaterThan (String value) {
						addCriterion("collection_novels >", value, "collection_novels");
						return (Criteria) this;
				}

				public Criteria andCollection_novelsGreaterThanOrEqualTo (String value) {
						addCriterion("collection_novels >=", value, "collection_novels");
						return (Criteria) this;
				}

				public Criteria andCollection_novelsLessThan (String value) {
						addCriterion("collection_novels <", value, "collection_novels");
						return (Criteria) this;
				}

				public Criteria andCollection_novelsLessThanOrEqualTo (String value) {
						addCriterion("collection_novels <=", value, "collection_novels");
						return (Criteria) this;
				}

				public Criteria andCollection_novelsLike (String value) {
						addCriterion("collection_novels like", value, "collection_novels");
						return (Criteria) this;
				}

				public Criteria andCollection_novelsNotLike (String value) {
						addCriterion("collection_novels not like", value, "collection_novels");
						return (Criteria) this;
				}

				public Criteria andCollection_novelsIn (List<String> values) {
						addCriterion("collection_novels in", values, "collection_novels");
						return (Criteria) this;
				}

				public Criteria andCollection_novelsNotIn (List<String> values) {
						addCriterion("collection_novels not in", values, "collection_novels");
						return (Criteria) this;
				}

				public Criteria andCollection_novelsBetween (String value1, String value2) {
						addCriterion("collection_novels between", value1, value2, "collection_novels");
						return (Criteria) this;
				}

				public Criteria andCollection_novelsNotBetween (String value1, String value2) {
						addCriterion("collection_novels not between", value1, value2, "collection_novels");
						return (Criteria) this;
				}

				public Criteria andSubscribed_novelsIsNull () {
						addCriterion("subscribed_novels is null");
						return (Criteria) this;
				}

				public Criteria andSubscribed_novelsIsNotNull () {
						addCriterion("subscribed_novels is not null");
						return (Criteria) this;
				}

				public Criteria andSubscribed_novelsEqualTo (String value) {
						addCriterion("subscribed_novels =", value, "subscribed_novels");
						return (Criteria) this;
				}

				public Criteria andSubscribed_novelsNotEqualTo (String value) {
						addCriterion("subscribed_novels <>", value, "subscribed_novels");
						return (Criteria) this;
				}

				public Criteria andSubscribed_novelsGreaterThan (String value) {
						addCriterion("subscribed_novels >", value, "subscribed_novels");
						return (Criteria) this;
				}

				public Criteria andSubscribed_novelsGreaterThanOrEqualTo (String value) {
						addCriterion("subscribed_novels >=", value, "subscribed_novels");
						return (Criteria) this;
				}

				public Criteria andSubscribed_novelsLessThan (String value) {
						addCriterion("subscribed_novels <", value, "subscribed_novels");
						return (Criteria) this;
				}

				public Criteria andSubscribed_novelsLessThanOrEqualTo (String value) {
						addCriterion("subscribed_novels <=", value, "subscribed_novels");
						return (Criteria) this;
				}

				public Criteria andSubscribed_novelsLike (String value) {
						addCriterion("subscribed_novels like", value, "subscribed_novels");
						return (Criteria) this;
				}

				public Criteria andSubscribed_novelsNotLike (String value) {
						addCriterion("subscribed_novels not like", value, "subscribed_novels");
						return (Criteria) this;
				}

				public Criteria andSubscribed_novelsIn (List<String> values) {
						addCriterion("subscribed_novels in", values, "subscribed_novels");
						return (Criteria) this;
				}

				public Criteria andSubscribed_novelsNotIn (List<String> values) {
						addCriterion("subscribed_novels not in", values, "subscribed_novels");
						return (Criteria) this;
				}

				public Criteria andSubscribed_novelsBetween (String value1, String value2) {
						addCriterion("subscribed_novels between", value1, value2, "subscribed_novels");
						return (Criteria) this;
				}

				public Criteria andSubscribed_novelsNotBetween (String value1, String value2) {
						addCriterion("subscribed_novels not between", value1, value2, "subscribed_novels");
						return (Criteria) this;
				}

				public Criteria andFootmarkIsNull () {
						addCriterion("footmark is null");
						return (Criteria) this;
				}

				public Criteria andFootmarkIsNotNull () {
						addCriterion("footmark is not null");
						return (Criteria) this;
				}

				public Criteria andFootmarkEqualTo (String value) {
						addCriterion("footmark =", value, "footmark");
						return (Criteria) this;
				}

				public Criteria andFootmarkNotEqualTo (String value) {
						addCriterion("footmark <>", value, "footmark");
						return (Criteria) this;
				}

				public Criteria andFootmarkGreaterThan (String value) {
						addCriterion("footmark >", value, "footmark");
						return (Criteria) this;
				}

				public Criteria andFootmarkGreaterThanOrEqualTo (String value) {
						addCriterion("footmark >=", value, "footmark");
						return (Criteria) this;
				}

				public Criteria andFootmarkLessThan (String value) {
						addCriterion("footmark <", value, "footmark");
						return (Criteria) this;
				}

				public Criteria andFootmarkLessThanOrEqualTo (String value) {
						addCriterion("footmark <=", value, "footmark");
						return (Criteria) this;
				}

				public Criteria andFootmarkLike (String value) {
						addCriterion("footmark like", value, "footmark");
						return (Criteria) this;
				}

				public Criteria andFootmarkNotLike (String value) {
						addCriterion("footmark not like", value, "footmark");
						return (Criteria) this;
				}

				public Criteria andFootmarkIn (List<String> values) {
						addCriterion("footmark in", values, "footmark");
						return (Criteria) this;
				}

				public Criteria andFootmarkNotIn (List<String> values) {
						addCriterion("footmark not in", values, "footmark");
						return (Criteria) this;
				}

				public Criteria andFootmarkBetween (String value1, String value2) {
						addCriterion("footmark between", value1, value2, "footmark");
						return (Criteria) this;
				}

				public Criteria andFootmarkNotBetween (String value1, String value2) {
						addCriterion("footmark not between", value1, value2, "footmark");
						return (Criteria) this;
				}

				public Criteria andAccount_balanceIsNull () {
						addCriterion("account_balance is null");
						return (Criteria) this;
				}

				public Criteria andAccount_balanceIsNotNull () {
						addCriterion("account_balance is not null");
						return (Criteria) this;
				}

				public Criteria andAccount_balanceEqualTo (Integer value) {
						addCriterion("account_balance =", value, "account_balance");
						return (Criteria) this;
				}

				public Criteria andAccount_balanceNotEqualTo (Integer value) {
						addCriterion("account_balance <>", value, "account_balance");
						return (Criteria) this;
				}

				public Criteria andAccount_balanceGreaterThan (Integer value) {
						addCriterion("account_balance >", value, "account_balance");
						return (Criteria) this;
				}

				public Criteria andAccount_balanceGreaterThanOrEqualTo (Integer value) {
						addCriterion("account_balance >=", value, "account_balance");
						return (Criteria) this;
				}

				public Criteria andAccount_balanceLessThan (Integer value) {
						addCriterion("account_balance <", value, "account_balance");
						return (Criteria) this;
				}

				public Criteria andAccount_balanceLessThanOrEqualTo (Integer value) {
						addCriterion("account_balance <=", value, "account_balance");
						return (Criteria) this;
				}

				public Criteria andAccount_balanceIn (List<Integer> values) {
						addCriterion("account_balance in", values, "account_balance");
						return (Criteria) this;
				}

				public Criteria andAccount_balanceNotIn (List<Integer> values) {
						addCriterion("account_balance not in", values, "account_balance");
						return (Criteria) this;
				}

				public Criteria andAccount_balanceBetween (Integer value1, Integer value2) {
						addCriterion("account_balance between", value1, value2, "account_balance");
						return (Criteria) this;
				}

				public Criteria andAccount_balanceNotBetween (Integer value1, Integer value2) {
						addCriterion("account_balance not between", value1, value2, "account_balance");
						return (Criteria) this;
				}

				public Criteria andMonthly_ticketsIsNull () {
						addCriterion("monthly_tickets is null");
						return (Criteria) this;
				}

				public Criteria andMonthly_ticketsIsNotNull () {
						addCriterion("monthly_tickets is not null");
						return (Criteria) this;
				}

				public Criteria andMonthly_ticketsEqualTo (Integer value) {
						addCriterion("monthly_tickets =", value, "monthly_tickets");
						return (Criteria) this;
				}

				public Criteria andMonthly_ticketsNotEqualTo (Integer value) {
						addCriterion("monthly_tickets <>", value, "monthly_tickets");
						return (Criteria) this;
				}

				public Criteria andMonthly_ticketsGreaterThan (Integer value) {
						addCriterion("monthly_tickets >", value, "monthly_tickets");
						return (Criteria) this;
				}

				public Criteria andMonthly_ticketsGreaterThanOrEqualTo (Integer value) {
						addCriterion("monthly_tickets >=", value, "monthly_tickets");
						return (Criteria) this;
				}

				public Criteria andMonthly_ticketsLessThan (Integer value) {
						addCriterion("monthly_tickets <", value, "monthly_tickets");
						return (Criteria) this;
				}

				public Criteria andMonthly_ticketsLessThanOrEqualTo (Integer value) {
						addCriterion("monthly_tickets <=", value, "monthly_tickets");
						return (Criteria) this;
				}

				public Criteria andMonthly_ticketsIn (List<Integer> values) {
						addCriterion("monthly_tickets in", values, "monthly_tickets");
						return (Criteria) this;
				}

				public Criteria andMonthly_ticketsNotIn (List<Integer> values) {
						addCriterion("monthly_tickets not in", values, "monthly_tickets");
						return (Criteria) this;
				}

				public Criteria andMonthly_ticketsBetween (Integer value1, Integer value2) {
						addCriterion("monthly_tickets between", value1, value2, "monthly_tickets");
						return (Criteria) this;
				}

				public Criteria andMonthly_ticketsNotBetween (Integer value1, Integer value2) {
						addCriterion("monthly_tickets not between", value1, value2, "monthly_tickets");
						return (Criteria) this;
				}

				public Criteria andMycommentsIsNull () {
						addCriterion("mycomments is null");
						return (Criteria) this;
				}

				public Criteria andMycommentsIsNotNull () {
						addCriterion("mycomments is not null");
						return (Criteria) this;
				}

				public Criteria andMycommentsEqualTo (String value) {
						addCriterion("mycomments =", value, "mycomments");
						return (Criteria) this;
				}

				public Criteria andMycommentsNotEqualTo (String value) {
						addCriterion("mycomments <>", value, "mycomments");
						return (Criteria) this;
				}

				public Criteria andMycommentsGreaterThan (String value) {
						addCriterion("mycomments >", value, "mycomments");
						return (Criteria) this;
				}

				public Criteria andMycommentsGreaterThanOrEqualTo (String value) {
						addCriterion("mycomments >=", value, "mycomments");
						return (Criteria) this;
				}

				public Criteria andMycommentsLessThan (String value) {
						addCriterion("mycomments <", value, "mycomments");
						return (Criteria) this;
				}

				public Criteria andMycommentsLessThanOrEqualTo (String value) {
						addCriterion("mycomments <=", value, "mycomments");
						return (Criteria) this;
				}

				public Criteria andMycommentsLike (String value) {
						addCriterion("mycomments like", value, "mycomments");
						return (Criteria) this;
				}

				public Criteria andMycommentsNotLike (String value) {
						addCriterion("mycomments not like", value, "mycomments");
						return (Criteria) this;
				}

				public Criteria andMycommentsIn (List<String> values) {
						addCriterion("mycomments in", values, "mycomments");
						return (Criteria) this;
				}

				public Criteria andMycommentsNotIn (List<String> values) {
						addCriterion("mycomments not in", values, "mycomments");
						return (Criteria) this;
				}

				public Criteria andMycommentsBetween (String value1, String value2) {
						addCriterion("mycomments between", value1, value2, "mycomments");
						return (Criteria) this;
				}

				public Criteria andMycommentsNotBetween (String value1, String value2) {
						addCriterion("mycomments not between", value1, value2, "mycomments");
						return (Criteria) this;
				}

				public Criteria andVipIsNull () {
						addCriterion("vip is null");
						return (Criteria) this;
				}

				public Criteria andVipIsNotNull () {
						addCriterion("vip is not null");
						return (Criteria) this;
				}

				public Criteria andVipEqualTo (Integer value) {
						addCriterion("vip =", value, "vip");
						return (Criteria) this;
				}

				public Criteria andVipNotEqualTo (Integer value) {
						addCriterion("vip <>", value, "vip");
						return (Criteria) this;
				}

				public Criteria andVipGreaterThan (Integer value) {
						addCriterion("vip >", value, "vip");
						return (Criteria) this;
				}

				public Criteria andVipGreaterThanOrEqualTo (Integer value) {
						addCriterion("vip >=", value, "vip");
						return (Criteria) this;
				}

				public Criteria andVipLessThan (Integer value) {
						addCriterion("vip <", value, "vip");
						return (Criteria) this;
				}

				public Criteria andVipLessThanOrEqualTo (Integer value) {
						addCriterion("vip <=", value, "vip");
						return (Criteria) this;
				}

				public Criteria andVipIn (List<Integer> values) {
						addCriterion("vip in", values, "vip");
						return (Criteria) this;
				}

				public Criteria andVipNotIn (List<Integer> values) {
						addCriterion("vip not in", values, "vip");
						return (Criteria) this;
				}

				public Criteria andVipBetween (Integer value1, Integer value2) {
						addCriterion("vip between", value1, value2, "vip");
						return (Criteria) this;
				}

				public Criteria andVipNotBetween (Integer value1, Integer value2) {
						addCriterion("vip not between", value1, value2, "vip");
						return (Criteria) this;
				}

				public Criteria andAccessIsNull () {
						addCriterion("access is null");
						return (Criteria) this;
				}

				public Criteria andAccessIsNotNull () {
						addCriterion("access is not null");
						return (Criteria) this;
				}

				public Criteria andAccessEqualTo (String value) {
						addCriterion("access =", value, "access");
						return (Criteria) this;
				}

				public Criteria andAccessNotEqualTo (String value) {
						addCriterion("access <>", value, "access");
						return (Criteria) this;
				}

				public Criteria andAccessGreaterThan (String value) {
						addCriterion("access >", value, "access");
						return (Criteria) this;
				}

				public Criteria andAccessGreaterThanOrEqualTo (String value) {
						addCriterion("access >=", value, "access");
						return (Criteria) this;
				}

				public Criteria andAccessLessThan (String value) {
						addCriterion("access <", value, "access");
						return (Criteria) this;
				}

				public Criteria andAccessLessThanOrEqualTo (String value) {
						addCriterion("access <=", value, "access");
						return (Criteria) this;
				}

				public Criteria andAccessLike (String value) {
						addCriterion("access like", value, "access");
						return (Criteria) this;
				}

				public Criteria andAccessNotLike (String value) {
						addCriterion("access not like", value, "access");
						return (Criteria) this;
				}

				public Criteria andAccessIn (List<String> values) {
						addCriterion("access in", values, "access");
						return (Criteria) this;
				}

				public Criteria andAccessNotIn (List<String> values) {
						addCriterion("access not in", values, "access");
						return (Criteria) this;
				}

				public Criteria andAccessBetween (String value1, String value2) {
						addCriterion("access between", value1, value2, "access");
						return (Criteria) this;
				}

				public Criteria andAccessNotBetween (String value1, String value2) {
						addCriterion("access not between", value1, value2, "access");
						return (Criteria) this;
				}
		}

		/**
		 * This class was generated by MyBatis Generator.
		 * This class corresponds to the database table readers
		 *
		 * @mbg.generated do_not_delete_during_merge Sat Jun 06 19:29:15 CST 2020
		 */
		public static class Criteria extends GeneratedCriteria {

				protected Criteria () {
						super();
				}
		}

		/**
		 * This class was generated by MyBatis Generator.
		 * This class corresponds to the database table readers
		 *
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		public static class Criterion {
				private String condition;

				private Object value;

				private Object secondValue;

				private boolean noValue;

				private boolean singleValue;

				private boolean betweenValue;

				private boolean listValue;

				private String typeHandler;

				public String getCondition () {
						return condition;
				}

				public Object getValue () {
						return value;
				}

				public Object getSecondValue () {
						return secondValue;
				}

				public boolean isNoValue () {
						return noValue;
				}

				public boolean isSingleValue () {
						return singleValue;
				}

				public boolean isBetweenValue () {
						return betweenValue;
				}

				public boolean isListValue () {
						return listValue;
				}

				public String getTypeHandler () {
						return typeHandler;
				}

				protected Criterion (String condition) {
						super();
						this.condition = condition;
						this.typeHandler = null;
						this.noValue = true;
				}

				protected Criterion (String condition, Object value, String typeHandler) {
						super();
						this.condition = condition;
						this.value = value;
						this.typeHandler = typeHandler;
						if (value instanceof List<?>) {
								this.listValue = true;
						} else {
								this.singleValue = true;
						}
				}

				protected Criterion (String condition, Object value) {
						this(condition, value, null);
				}

				protected Criterion (String condition, Object value, Object secondValue, String typeHandler) {
						super();
						this.condition = condition;
						this.value = value;
						this.secondValue = secondValue;
						this.typeHandler = typeHandler;
						this.betweenValue = true;
				}

				protected Criterion (String condition, Object value, Object secondValue) {
						this(condition, value, secondValue, null);
				}
		}
}