package cn.xy.novelwebproject.dao;

import cn.xy.novelwebproject.bean.Footmarks;
import cn.xy.novelwebproject.bean.FootmarksExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface FootmarksMapper {
		/**
		 * This method was generated by MyBatis Generator.
		 * This method corresponds to the database table footmarks
		 *
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		long countByExample (FootmarksExample example);

		/**
		 * This method was generated by MyBatis Generator.
		 * This method corresponds to the database table footmarks
		 *
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		int deleteByExample (FootmarksExample example);

		/**
		 * This method was generated by MyBatis Generator.
		 * This method corresponds to the database table footmarks
		 *
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		int insert (Footmarks record);

		/**
		 * This method was generated by MyBatis Generator.
		 * This method corresponds to the database table footmarks
		 *
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		int insertSelective (Footmarks record);

		/**
		 * This method was generated by MyBatis Generator.
		 * This method corresponds to the database table footmarks
		 *
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		List<Footmarks> selectByExample (FootmarksExample example);

		/**
		 * This method was generated by MyBatis Generator.
		 * This method corresponds to the database table footmarks
		 *
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		int updateByExampleSelective (@Param("record") Footmarks record, @Param("example") FootmarksExample example);

		/**
		 * This method was generated by MyBatis Generator.
		 * This method corresponds to the database table footmarks
		 *
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		int updateByExample (@Param("record") Footmarks record, @Param("example") FootmarksExample example);
}