package cn.xy.novelwebproject.dao;

import cn.xy.novelwebproject.bean.Noveltype;
import cn.xy.novelwebproject.bean.NoveltypeExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface NoveltypeMapper {
		/**
		 * This method was generated by MyBatis Generator.
		 * This method corresponds to the database table noveltype
		 *
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		long countByExample (NoveltypeExample example);

		/**
		 * This method was generated by MyBatis Generator.
		 * This method corresponds to the database table noveltype
		 *
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		int deleteByExample (NoveltypeExample example);

		/**
		 * This method was generated by MyBatis Generator.
		 * This method corresponds to the database table noveltype
		 *
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		int deleteByPrimaryKey (Integer id);

		/**
		 * This method was generated by MyBatis Generator.
		 * This method corresponds to the database table noveltype
		 *
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		int insert (Noveltype record);

		/**
		 * This method was generated by MyBatis Generator.
		 * This method corresponds to the database table noveltype
		 *
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		int insertSelective (Noveltype record);

		/**
		 * This method was generated by MyBatis Generator.
		 * This method corresponds to the database table noveltype
		 *
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		List<Noveltype> selectByExample (NoveltypeExample example);

		/**
		 * This method was generated by MyBatis Generator.
		 * This method corresponds to the database table noveltype
		 *
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		Noveltype selectByPrimaryKey (Integer id);

		/**
		 * This method was generated by MyBatis Generator.
		 * This method corresponds to the database table noveltype
		 *
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		int updateByExampleSelective (@Param("record") Noveltype record, @Param("example") NoveltypeExample example);

		/**
		 * This method was generated by MyBatis Generator.
		 * This method corresponds to the database table noveltype
		 *
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		int updateByExample (@Param("record") Noveltype record, @Param("example") NoveltypeExample example);

		/**
		 * This method was generated by MyBatis Generator.
		 * This method corresponds to the database table noveltype
		 *
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		int updateByPrimaryKeySelective (Noveltype record);

		/**
		 * This method was generated by MyBatis Generator.
		 * This method corresponds to the database table noveltype
		 *
		 * @mbg.generated Sat Jun 06 19:29:15 CST 2020
		 */
		int updateByPrimaryKey (Noveltype record);
}